

INSERT INTO SMETSTBND.GMMOVI0F   SELECT * FROM  SMEDATREP.GMMOVI0F

COMMIT 

INSERT INTO SMETSTBND.GMQUAN0F  SELECT * FROM SMEDATREP.GMQUAN0F

COMMIT

INSERT INTO SMETSTBND.CQLOTT0F SELECT * FROM  SMEDATREP.CQLOTT0F 



DELETE  FROM SMEDATBND.GMMOVI0F 
WHERE S冷URE IN (SELECT S冷URE FROM SMEDATREP.GMMOVI0F)

COMMIT


SELECT * FROM smeDATREP.gmquan0f WHERE g呃dmg='F2'


SELECT DISTINCT(E你GEN), COUNT(E你GEN) FROM SMEDATFDA.BRENTI0F  
WHERE E劫RAG='PVE'
GROUP BY E你GEN 



AND E低RAG='0251305'
