

WITH X AS (
SELECT S§TRAG,S§CRAG,  
LOWER(  SUBSTR(S§LIBE, 77, 256))  "PEC"  
FROM SMEDATFDA.BRESCO0F 
WHERE S§TRAG='CLI' AND S§TEST='£51'  
AND S§LIBE LIKE '%@%' 
) 
SELECT E§STAT, E§TRAG, E§CRAG, E§NMNE, E§RAGS, E§RAGA, E§INDI, E§LOCA, E§CAPA, E§PROV,  E§CPAI, E§COFI, X.PEC  
FROM SMEDATFDA.BRENTI0F INNER JOIN X ON E§CRAG=X.S§CRAG 
WHERE E§TRAG='CLI'  
      AND E§DINV <= YEAR(CURRENT_DATE)*10000
                  + MONTH(CURRENT_DATE)*100
                  + DAY(CURRENT_DATE)
      AND E§DFNV >= YEAR(CURRENT_DATE)*10000
                  + MONTH(CURRENT_DATE)*100
                  + DAY(CURRENT_DATE) 
                  
WITH Y AS (
SELECT E§CRAG,E§CCON,E§TCON  FROM SMEDATFDA.BRENTI0F WHERE E§TRAG='PVE' AND E§STAT='10'
      AND E§DINV <= YEAR(CURRENT_DATE)*10000
                  + MONTH(CURRENT_DATE)*100
                  + DAY(CURRENT_DATE)
      AND E§DFNV >= YEAR(CURRENT_DATE)*10000
                  + MONTH(CURRENT_DATE)*100
                  + DAY(CURRENT_DATE) 
) 
SELECT  DISTINCT E§CCON FROM SMEDATFDA.HHFTPVE INNER JOIN Y ON CODPVE=E§CRAG  
WHERE ANNOFT>=2020  AND E§TCON='CLI'




SELECT J§DATA,COUNT(J§DATA) AS  TOTREC FROM SMEDATFDA.GMFOTO0F 
GROUP BY J§DATA 


SELECT * FROM SMEDATFDA.HHSPART WHERE ANNO=2022 

MERGE INTO target_table USING source_table ON match-condition
{WHEN [NOT] MATCHED 
          THEN [UPDATE SET ...|DELETE|INSERT VALUES ....|SIGNAL ...]}
[ELSE IGNORE]



SELECT * FROM SMEDATBND.RIFATT09 

MERGE INTO SMETSTBND.RIFATT09  AS TG 
USING SMETSTBND.RIFATTWK AS SR
ON (TG.IDRECORD = SR.IDRECORD) 
WHEN MATCHED THEN 
UPDATE SET
 (
  TG.IDRECORD , TG.PVE_SERV , TG.DTOR_CLIE , TG.ORD_CLIEN, TG.DDT_DATE , TG.CLI_CONCE , TG.DDT_NUM  , TG.COD_ART ,  
  TG.NUM_ROW  , TG.QTA_ART  , TG.REASON , TG.YEAR_CONS , TG.TIP_MOV  , TG.DT_SYS  , TG.COMPANY , TG.X_FLG01 ,   
  TG.X_FLG02 , TG.X_FLG03  , TG.X_FLG04 , TG.X_FLG05 , TG.X_FLD01, TG.X_FLD02 , TG.X_FLD03, TG.X_FLD04 , TG.X_FLD05 
  )
  = 
  (
  SR.IDRECORD , SR.PVE_SERV , SR.DTOR_CLIE , SR.ORD_CLIEN, SR.DDT_DATE , SR.CLI_CONCE , SR.DDT_NUM  , SR.COD_ART ,  
  SR.NUM_ROW  , SR.QTA_ART  , SR.REASON , SR.YEAR_CONS , SR.TIP_MOV  , SR.DT_SYS  , SR.COMPANY , SR.X_FLG01 ,   
  SR.X_FLG02 , SR.X_FLG03  , SR.X_FLG04 , SR.X_FLG05 , SR.X_FLD01, SR.X_FLD02 , SR.X_FLD03, SR.X_FLD04 , SR.X_FLD05 
  )
WHEN NOT MATCHED THEN 
INSERT 
 (
  TG.IDRECORD , TG.PVE_SERV , TG.DTOR_CLIE, TG.ORD_CLIEN, TG.DDT_DATE , TG.CLI_CONCE , TG.DDT_NUM  , TG.COD_ART ,  
  TG.NUM_ROW  , TG.QTA_ART  , TG.REASON , TG.YEAR_CONS , TG.TIP_MOV  , TG.DT_SYS  , TG.COMPANY , TG.X_FLG01 ,   
  TG.X_FLG02 , TG.X_FLG03  , TG.X_FLG04 , TG.X_FLG05 , TG.X_FLD01, TG.X_FLD02 , TG.X_FLD03, TG.X_FLD04 , TG.X_FLD05 
  )
  VALUES 
  (
  SR.IDRECORD , SR.PVE_SERV , SR.DTOR_CLIE , SR.ORD_CLIEN, SR.DDT_DATE , SR.CLI_CONCE , SR.DDT_NUM  , SR.COD_ART ,  
  SR.NUM_ROW  , SR.QTA_ART  , SR.REASON , SR.YEAR_CONS , SR.TIP_MOV  , SR.DT_SYS  , SR.COMPANY , SR.X_FLG01 ,   
  SR.X_FLG02 , SR.X_FLG03  , SR.X_FLG04 , SR.X_FLG05 , SR.X_FLD01, SR.X_FLD02 , SR.X_FLD03, SR.X_FLD04 , SR.X_FLD05 
  )

  
SELECT MIN(IDRECORD) FROM SMETSTBND.RIFATT09 
WHERE X_FLG01 IN ('', 'C');



  INSERT INTO SMETSTBND.RIFATTWK (SELECT * FROM SMETSTBND.RIFATT09 WHERE IDRECORD >5710)
  
  
    SELECT IDRECORD, COUNT(IDRECORD) FROM SMETSTBND.RIFATT09 
  GROUP BY IDRECORD HAVING COUNT(IDRECORD) >1 
  
  
  DELETE FROM SMETSTBND.RIFATTWK WHERE IDRECORD= 9999999999