
SELECT * FROM EDO_ESTR_ORDINATO_TEST eeot 

SELECT DISTINCT trim(custaccount), cast(deliverydate AS dec(14,0)) FROM CED.AXDOCLINE  



SELECT * FROM NBFDATSTBN.IDOCHEADER i  


CREATE TABLE ced.krndstr ( keystr20 char(20)) 


SELECT * FROM CED.AXDOCLINE

SELECT MAX(LENGTH(TRIM(CUSTACCOUNT))) FROM CED.AXDOCLINE

UPDATE CED.AXDOCLINE 
SET CUSTACCOUNT='0'||substr(TRIM(CUSTACCOUNT), 2, 9)

SELECT DATE(DELIVERYDATE, 

SELECT REPLACE(REPLACE(LEFT(TO_CHAR(DELIVERYDATE), 10),'-', ''), '.', '') FROM CED.AXDOCLINE 

SELECT TRIM(REPLACE(SUBSTR(TO_CHAR(DATE(DELIVERYDATE)), 3, 8), '-', '')) FROM CED.AXDOCLINE

SELECT 
REPLACE(REPLACE(LEFT(TO_CHAR(DELIVERYDATE), 15),'-', ''), '.', '') 
FROM CED.AXDOCLINE A 

COMMIT

SELECT * FROM NBFDATSTBN.IDOCLINE

INSERT INTO CED.IDOCLINE (DCLID, DCLORDCODE, DCLLINENRO, DCLLINETYP, DCLTIMESTP, DCLPRDCODE, DCLCONFIG, DCLQTA, DCLNTRIG, 
DCLFLD1,
DCLNOTE  
) 
SELECT RRN(A), 
LEFT(TRIM(CUSTACCOUNT)
||
TRIM(SALESID)
||
TRIM(REPLACE(SUBSTR(TO_CHAR(DATE(DELIVERYDATE)), 3, 8), '-', '')), 21), 
INT(LINENUM), 
'001', 
REPLACE(REPLACE(LEFT(TO_CHAR(DELIVERYDATE), 15),'-', ''), '.', '') ,
--DELIVERYDATE, 
ITEMID, 
'000', 
QTYORDERED, 
LINEAMOUNT, 
TIPO_ORDINE, 
CustomerRef 
FROM CED.AXDOCLINE A


COMMIT

FROM CED.AXDOCLINE  A


SELECT MAX(LINENUM) FROM CED.AXDOCLINE 


SELECT  DISTINCT DCLORDCODE,  RRN(A) FROM CED.IDOCLINE A 


SELECT DISTINCT SALESID FROM CED.AXDOCLINE



CREATE TABLE QTEMP.ORDERID (IDORD CHAR(30), KORD DEC(10))

INSERT INTO QTEMP.ORDERID 
SELECT DCLORDCODE, 
MIN(DCLID) OVER(PARTITION BY DCLORDCODE) AS ORDID 
   FROM CED.IDOCLINE  
   
   
UPDATE CED.IDOCLINE A 
SET A.DCLID = ( SELECT B.KORD FROM QTEMP.ORDERID B WHERE B.IDORD=A.DCLORDCODE )

