

-- estrazione di tutte le P.IVA estero che presentano la ripetizione del codice Nazione nel campo Partita IVA Estero
SELECT E§CRAG, E§STAT, E§RAGS, E§CNAZ, E§CPAI, E§CPAE, LTRIM(SUBSTRING(E§CPAE , 3 , 27)) AS NEWPAE FROM SMETSTFDA.BRENTI0F   
WHERE  E§DFNV >=  VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD')   
AND E§CPAE<>''
AND E§CNAZ <>'IT' AND E§CNAZ<>''   
AND TRIM(E§CNAZ) = LEFT(E§CPAE, 2) 


-- toglo il prefisso del codice nazione dal capo e§cpae e allineo a sx il resto 
UPDATE SMETSTFDA.BRENTI0F 
SET E§CPAE= LTRIM(SUBSTRING(E§CPAE , 3 , 27)) ,
E§ORAG = '173000' ,   
E§DTAG = '20240702' ,  
E§USAG = 'SQLEDP01'
WHERE  E§DFNV >=  VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD')   
AND E§CPAE<>''
AND E§CNAZ <>'IT'    
AND TRIM(E§CNAZ) = LEFT(E§CPAE, 2) 


SELECT E§CRAG, E§RAGS, E§RAGA, E§STAT, E§INDI, E§LOCA, E§CNAZ, E§CPAI, E§CPAE FROM SMETSTFDA.BRENTI0F 
WHERE  E§DFNV >=  VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD')
AND E§USAG='SQLEDP01'


SELECT DISTINCT E§CNAZ FROM SMETSTFDA.BRENTI0F 
