SELECT * FROM (
SELECT  MIN(S1.UNSENTBLCD) AS CLI, S1.UNSENTSHCD AS PVE, 
(SELECT TRIM(P£CDVA) FROM SMEDATBND.C£ESO00F WHERE P£TPRC='PVE' AND P£NUMP='D15' AND P£CD01=S1.UNSENTSHCD) AS INSEGNA,
 min(B.E§ZONA) AS ZONA,
 min(S1.DOC) AS TIPODOC,
 S1.UNSDOCNUMB AS NUMDOC,
 max(S1.UNSDATAISS) AS DOCDATA,
 max(S1.DESCR) AS DOCINFO, sum(S1.DARE) AS DARE, sum(S1.AVERE) AS AVERE, sum(S1.AVERE)-sum(S1.DARE) AS SALDO
FROM (
SELECT
CASE WHEN S.UNSDOCTYPE = 'F'  THEN 'FATTURA'  
     WHEN S.UNSDOCTYPE = 'D'  THEN 'DDT'  
     WHEN S.UNSDOCTYPE = 'P'  THEN 'INCASSO'  
     WHEN S.UNSDOCTYPE = 'A'  THEN 'NOTA CREDITO'  
     ELSE 'ND' END AS DOC,
CASE WHEN S.UNSDOCTYPE IN('F', 'D') THEN S.UNSNOTE ELSE '' END AS DESCR,
CASE WHEN S.UNSDOCTYPE IN('F', 'D') THEN S.UNSVALUE ELSE 0 END AS DARE,
CASE WHEN S.UNSDOCTYPE IN('P', 'A') THEN S.UNSVALUE ELSE 0 END AS AVERE, S.*
FROM NBFDATBND.BSOSPESI0F S
) AS S1
INNER JOIN SMEDATBND.BRENTI0F B ON (B.E§TRAG='PVE' AND B.E§CRAG=S1.UNSENTSHCD) 
AND B.E§DINV <= VARCHAR_FORMAT(CURRENT_DATE,'YYYYMMDD') AND COALESCE(NULLIF(B.E§DFNV, 0),99999999) >= VARCHAR_FORMAT(CURRENT_DATE,'YYYYMMDD')
WHERE S1.UNSENTBLCD='528539 '  
GROUP BY S1.UNSENTSHCD, S1.UNSDOCNUMB
UNION 
SELECT  max(S1.UNSENTBLCD) AS CLI, S1.UNSENTSHCD AS PVE, 
(SELECT TRIM(P£CDVA) FROM SMEDATBND.C£ESO00F WHERE P£TPRC='PVE' AND P£NUMP='D15' AND P£CD01=S1.UNSENTSHCD) AS INSEGNA,
 max(B.E§ZONA) AS ZONA,
 min(S1.DOC) AS TIPODOC,
 S1.UNSDOCNUMB AS NUMDOC,max(S1.UNSDATAISS) AS DOCDATA,
 max(S1.DESCR) AS DOCINFO, sum(S1.DARE) AS DARE, sum(S1.AVERE) AS AVERE, sum(S1.AVERE)-sum(S1.DARE) AS SALDO
FROM (
SELECT
CASE WHEN S.UNSDOCTYPE = 'F'  THEN 'FATTURA'  
     WHEN S.UNSDOCTYPE = 'D'  THEN 'DDT'  
     WHEN S.UNSDOCTYPE = 'P'  THEN 'INCASSO'  
     WHEN S.UNSDOCTYPE = 'A'  THEN 'NOTA CREDITO'  
     ELSE 'ND' END AS DOC,
CASE WHEN S.UNSDOCTYPE IN('F', 'D') THEN S.UNSNOTE ELSE '' END AS DESCR,
CASE WHEN S.UNSDOCTYPE IN('F', 'D') THEN S.UNSVALUE ELSE 0 END AS DARE,
CASE WHEN S.UNSDOCTYPE IN('P', 'A') THEN S.UNSVALUE ELSE 0 END AS AVERE, S.*
FROM NBFDATBND.BSOSPESI0F S
) AS S1
INNER JOIN SMEDATBND.BRENTI0F B ON (B.E§TRAG='PVE' AND B.E§CRAG=S1.UNSENTSHCD) 
AND B.E§DINV <= VARCHAR_FORMAT(CURRENT_DATE,'YYYYMMDD') AND COALESCE(NULLIF(B.E§DFNV, 0),99999999) >= VARCHAR_FORMAT(CURRENT_DATE,'YYYYMMDD')
WHERE S1.UNSENTBLCD='528539 ' 
AND S1.AVERE>0
GROUP BY S1.UNSENTSHCD, S1.UNSDOCNUMB
) AS T1


ORDER BY T1.NUMDOC, T1.TP, T1.DOCDATA


SELECT * FROM NBFDATBND.BSOSPESI0F WHERE UNSENTBLCD='528539'








SELECT S1.TP, '' AS TIPO, S1.UNSENTBLCD AS CLI, S1.UNSENTSHCD AS PVE, B.E§ZONA AS ZONA, S1.UNSNUMDOCB AS NUMDOC, S1.UNSDATAMOV AS DOCDATA, S1.UNSNOTE AS DOCINFO, S1.DARE AS DARE, S1.AVERE AS AVERE, S1.AVERE-S1.DARE AS SALDO
FROM (
SELECT
CASE WHEN S.UNSDOCTYPE IN('F', 'D') THEN '0' ELSE '1' END AS TP,
CASE WHEN S.UNSDOCTYPE IN('F', 'D') THEN S.UNSVALUE ELSE 0 END AS DARE,
CASE WHEN S.UNSDOCTYPE IN('P', 'A') THEN S.UNSVALUE ELSE 0 END AS AVERE, S.*
FROM NBFDATBND.BSOSPESI0F S
) AS S1
INNER JOIN SMEDATBND.BRENTI0F B ON (B.E§TRAG='PVE' AND B.E§CRAG=S1.UNSENTSHCD)
AND B.E§DINV <= VARCHAR_FORMAT(CURRENT_DATE,'YYYYMMDD') AND COALESCE(NULLIF(B.E§DFNV, 0),99999999) >= VARCHAR_FORMAT(CURRENT_DATE,'YYYYMMDD')
-- WHERE S1.UNSENTBLCD='226037'
WHERE S1.UNSENTBLCD='528539 ' 
AND S1.AVERE>0
) AS T1
ORDER BY T1.NUMDOC, T1.TP, T1.DOCDATA


SELECT
CASE WHEN S.UNSDOCTYPE IN('F', 'D') THEN S.UNSNOTE ELSE '' END AS DESCR,
CASE WHEN S.UNSDOCTYPE IN('F', 'D') THEN S.UNSVALUE ELSE 0 END AS DARE,
CASE WHEN S.UNSDOCTYPE IN('P', 'A') THEN S.UNSVALUE ELSE 0 END AS AVERE, S.*
FROM NBFDATBND.BSOSPESI0F S 


SELECT E§CRAG,E§NMNE, E§RAGS, E§RAGA,P£CDVA
--LENGTH(TRIM(P£CDVA)), COUNT(P£CDVA) 
FROM SMEDATBND.BRENTI0F INNER JOIN SMEDATBND.C£ESO00F  
ON P£TPRC=E§TRAG AND P£CD01=E§CRAG 
WHERE E§TRAG='PVE' AND P£NUMP='D15'  AND LENGTH(TRIM(P£CDVA))>30 

SELECT TRIM(P£CDVA) FROM SMEDATBND.C£ESO00F WHERE P£TPRC='PVE' AND P£NUMP='D15' AND P£CD01

GROUP BY LENGTH(TRIM(P£CDVA))
--P£TPRC='PVE' AND P£CD01='9172186' 


