SELECT * FROM ced.sipacard 

SELECT * FROM SMETSTBND.TABEL00F WHERE TTSETT ='XPS' 

DELETE FROM SMEDATBND.TABEL00F WHERE TTSETT ='XPS' 

INSERT INTO SMEDATBND.TABEL00F (TTSETT, TTELEM, TTDESC, TTLIBE, TTUSER) 
SELECT 'XPS', TESSERA, LEFT(ASSEGNATO, 30) , 'T', 'CODPDC: '||CODPDC FROM CED.SIPACARD
 
SELECT * FROM SMEDATBND.TABEL00F WHERE TTSETT='XPS'
 

SELECT * FROM SMEDATBND.TABEL00F  
WHERE  TTSETT='ZAG'
 
SELECT * FROM SMEDATBND.C£CONR0F 
WHERE C£NUMP='ZAG'
 

SELECT * FROM SMETSTBND.MEDAV00F mf  WHERE MD£DTU=230409

INSERT INTO CED.PARES00F 
SELECT * FROM SMEDATBND.PARES01L WHERE PE£PGM IN ('V5BO01CL' , 'XV50019') 
AND LEFT(PE£UTE, 2) IN ('F2', 'F3', 'F4', 'F6', 'F7')


DELETE  FROM SMETSTBND.PARES01L WHERE PE£PGM IN ('V5BO01CL' , 'XV50019') 
AND LEFT(PE£UTE, 2) IN ('F2', 'F3', 'F4', 'F6', 'F7')
 

INSERT INTO NBFDATSTBN.IDOCHEADER 
SELECT * FROM CED.IDOCHEADER 

INSERT INTO NBFDATSTBN.IDOCLINE 
SELECT * FROM CED.IDOCLINE 


SELECT *
--DISTINCT C£CDVA 
FROM CED.C£CONR0F

SELECT * FROM SMETSTBND.BRENTI0F WHERE E§TRAG='PVE'
 

SELECT * FROM SMETSTBND.TABEL00F WHERE TTSETT='XGI' 
AND LEFT(TTLIBE, 2) IN ('F2', 'F3', 'F4', 'F6', 'F7') 
ORDER BY LEFT(TTLIBE, 2)


SELECT * FROM SMEDATBND.C£CONR0F WHERE C£NUMP='X68'

SELECT DISTINCT C£CD01 FROM SMEDATBND.C£CONR0F WHERE C£NUMP='X68' AND C£TPRC='PVE'


CREATE TABLE QTEMP.BNDTRATT (TRT CHAR(3))

INSERT INTO QTEMP.BNDTRATT 
SELECT DISTINCT SUBSTR(TTELEM, 3, 3) FROM SMEDATBND.TABEL00F WHERE TTSETT='XGI'  

SELECT DISTINCT C£CDVA FROM SMEDATBND.C£CONR0F WHERE C£NUMP='X68' AND C£TPRC='PVE' 
AND LEFT(C£CDVA,3) NOT IN (SELECT TRT FROM QTEMP.BNDTRATT)

INSERT INTO CED.C£CONR0FWK (
SELECT * FROM SMEDATBND.C£CONR0F WHERE C£NUMP='X68'  AND C£TPRC='PVE'
)

DELETE FROM SMETSTBND.C£CONR0F WHERE C£NUMP='X68'

UPDATE CED.C£CONR0FWK A 
SET A.C£NUMP = (SELECT B.C£NUMP FROM CED.C£CONR0F B WHERE B.C£CD01=A.C£CD01) 
WHERE A.C£CD01 IN (SELECT C.C£CD01 FROM CED.C£CONR0F C) 

SELECT COUNT(*) FROM CED.C£CONR0FWK WHERE C£NUMP='X68' 

UPDATE CED.C£CONR0FWK 
SET C£NUMP='GC1' 
WHERE C£NUMP='X68'

INSERT INTO SMEDATBND.C£CONR0F SELECT * FROM CED.C£CONR0FWK 

INSERT INTO NBFDATSTBN.IDOCHEADER 
SELECT * FROM CED.IDOCHEADER WHERE DCHPLTCODE='F4' 

INSERT INTO NBFDATSTBN.IDOCLINE 
SELECT * FROM CED.IDOCLINE WHERE DCLID IN (
SELECT DCHID FROM NBFDATSTBN.IDOCHEADER )

COMMIT


SELECT * FROM SMETSTBND.V5TDOC0F WHERE T§DTIN=20230409 AND T§OGIN='XNBI01'  

UPDATE SMETSTBND.V5TDOC0F 
SET T§STAT='10' 
WHERE T§DTIN>=20230409 AND T§OGIN='XNBI01'  

SELECT T§CDMG, COUNT(T§CDMG) FROM SMETSTBND.V5TDOC0F --wHERE T§TDOC='DA'  AND T§TMOD='001'
GROUP BY T§CDMG                               


SELECT * FROM SMETSTBND.V5RDOC0F WHERE R§DTIN=20230409 AND R§OGIN='XNBI01' 

UPDATE SMETSTBND.V5RDOC0F 
SET R§STAT='10' 
WHERE R§DTIN>=20230409 AND R§OGIN='XNBI01'  


DELETE  FROM SMETSTBND.C£CONR0F WHERE LEFT(C£NUMP, 2)='GC' 


SELECT E§COD1, C£CDVA, C£CD01 FROM CED.C£CONR0FWK LEFT JOIN SMETSTBND.BRENTI0F 
ON C£CD01=E§CRAG 
WHERE E§TRAG='PVE' 

UPDATE CED.C£CONR0FWK 
SET C£CDVA='F3'||TRIM(C£CDVA) 
WHERE C£CD01 IN (
SELECT E§CRAG FROM SMETSTBND.BRENTI0F 
WHERE E§TRAG='PVE' AND E§COD1='F7'
)


SELECT * FROM CED.C£CONR0FWK 
WHERE LENGTH(TRIM(C£CDVA))<='4'

SELECT DISTINCT C£CDVA FROM CED.C£CONR0FWK 
WHERE SUBSTR(C£CDVA, 3,1)='M' 

 DELETE FROM SMETSTBND.V5TDOC0F WHERE 
 T§TDOC='OA'            AND 
 T§TMOD='001'           AND
 T§OGIN IN ('XNBI01')   AND 
 T§DTIN>=20230412     
 
 
 DELETE FROM SMETSTBND.V5RDOC0F WHERE 
 R§TDOC='OA'            AND 
 R§TRIG='001'           AND
 R§OGIN IN ('XNBI01')   AND 
 R§DTIN>=20230412     
 
 R§DTIN>=20230412  AND R§OGIN IN ('XNBI01')  
 
SELECT * FROM smedatfda.tabel00f WHERE ttsett='XGI' 
AND 
 SELECT * FROM smetstbnd.tabel00f WHERE ttsett='XGI'
 
DELETE FROM SMETSTBND.TABEL00F WHERE TTSETT='XGI'

INSERT INTO SMETSTBND.TABEL00F 
SELECT * FROM SMEDATBND.TABEL00F WHERE TTSETT='XGI' 

SELECT DISTINCT C£CDVA FROM CED.C£CONR0FWK WHERE C£CDVA 
NOT IN (SELECT TTELEM FROM SMEDATBND.TABEL00F WHERE TTSETT='XGI') ORDER BY C£CDVA

SELECT * FROM SMEDATBND.TABEL00F WHERE TTSETT='XGI' 
AND LEFT(TTLIBE,2)='F3' 

INSERT INTO SMETSTBND.BRENTI0F 
SELECT * FROM SMEDATFDA.BRENTI0F WHERE E§TRAG='VET' 

AND LEFT(E§CRAG, 1)='L'


SELECT * FROM SMETSTBND.V5TDOC0F WHERE T§CDMG='F3' 

UPDATE SMETSTBND.V5TDOC0F  
SET T§VET1='' WHERE T§CDMG<>'F1' AND 
T§DTIN=20230410 AND T§OGIN='XNBI01' 
AND T§TDOC='DA' AND T§TMOD='001'


SELECT t§zona, count(t§zona) FROM SMETSTBND.V5TDOC0F WHERE T§CDMG='F7' 
GROUP BY t§zona


CREATE TABLE CED.ZONAGIRO(ZONA CHAR(3), GIRO CHAR(5))

INSERT INTO CED.ZONAGIRO
SELECT DISTINCT t§zona,t§cod1 FROM smetstbnd.v5tdoc0f WHERE T§CDMG='F7'  

UPDATE SMETSTBND.V5TDOC0F 
SET T§COD1='F3M09' 
WHERE T§ZONA='A01'
AND T§CDMG='F3' 


UPDATE SMETSTBND.V5TDOC0F A
SET A.T§COD1=(SELECT B.GIRO FROM CED.ZONAGIRO B WHERE  B.ZONA=A.T§ZONA)
WHERE A.T§CDMG='F3' AND 
A.T§DTIN>=20230411  AND A.T§OGIN IN ('XNBI01') 

SELECT DISTINCT C£CDVA FROM CED.C£CONR0FWK WHERE LEFT(C£CDVA, 2)='F2' 


SELECT * FROM SMETSTBND.TABEL00F WHERE TTSETT='XGI' AND (LEFT(TTELEM, 2)='F2' OR LEFT(TTUSER,2)='F2')

SELECT E§TRAG, E§CRAG, E§RAGS FROM SMEDATFDA.BRENTI0F WHERE E§TRAG='VET' 


SELECT * FROM SMEDATBND.TABEL00F WHERE TTSETT='XGI' ORDER BY LEFT(TTLIBE,2)


DELETE FROM SMETSTBND.V5RDOC0F WHERE R§TDOC='OA' AND 
R§NDOC IN (
SELECT T§NDOC FROM SMETSTBND.V5TDOC0F  WHERE T§DTIN=20230412
AND T§OGIN='XNBI01'
)

DELETE  FROM SMETSTBND.V5TDOC0F  WHERE T§DTIN=20230412


SELECT * FROM NBFDATSTBN.XNBIHE0F xf 
WHERE H§IDRE NOT IN (SELECT L§IDRE FROM NBFDATSTBN.XNBILN0F xf2)

INSERT INTO SMEDATBND.BRENTI0F 

SELECT E§CRAG, E§NMNE, E§RAGS FROM SMEDATFDA.BRENTI0F WHERE E§TRAG='VET' 
                          AND E§DINV <= YEAR(CURRENT_DATE)*10000
                                            + MONTH(CURRENT_DATE)*100
                                            + DAY(CURRENT_DATE)
                          AND E§DFNV >= YEAR(CURRENT_DATE)*10000
                                            + MONTH(CURRENT_DATE)*100
                                            + DAY(CURRENT_DATE)
                                            
                                            
DELETE FROM SMETSTBND.TABEL00F WHERE TTSETT='XCI'
                                            
INSERT INTO SMETSTBND.TABEL00F
SELECT * FROM SMEDATBND.TABEL00F tf WHERE TTSETT='XCI'                                           