

-- su as400  trovo il valore minimo del campo idrecord da caricare/aggiornare   
SET @IDRSTART = (
SELECT MIN(IDRECORD) FROM SMETSTBND.RIFATT09 
WHERE X_FLG01 IN ('', 'C')
) ;

-- su SRVSQL01 remoto  carico il file vuoto rifattwk leggendo per recordid maggiore uguale 
-- al valore trovato al punto sopra.

declare c1 as (SELECT * FROM dbo.OUT_0009_RIFATTURAZIONE where RECORDID >= @IDRSTART; 

DOW SQLCODE = 0; 
	EXEC SQL FETCH C1 INTO :rifattwk; 
if sqlcode <> 0;
  leave;
endif;

-- con il file di work appena creato lancio la seguente query: 

MERGE INTO SMETSTBND.RIFATT09  AS TG 
USING SMETSTBND.RIFATTWK AS SR 
ON (TG.IDRECORD = SR.IDRECORD ) 
WHEN MATCHED THEN 
UPDATE SET
 (
  IDRECORD , PVE_SERV , DTOR_CLIE , ORD_CLIEN , DDT_DATE , CLI_CONCE , DDT_NUM  , COD_ART ,  
  NUM_ROW  , QTA_ART  , REASON  , YEAR_CONS , TIP_MOV  , DT_SYS  , COMPANY , X_FLG01 ,   
  X_FLG02  , X_FLG03  , X_FLG04 , X_FLG05 , X_FLD01 , X_FLD02 , X_FLD03 , X_FLD04 , X_FLD05 
  )
  = 
  (
  SR.IDRECORD , SR.PVE_SERV , SR.DTOR_CLIE, SR.ORD_CLIEN , SR.DDT_DATE , SR.CLI_CONCE , SR.DDT_NUM  , SR.COD_ART ,  
  SR.NUM_ROW  , SR.QTA_ART  , SR.REASON , SR.YEAR_CONS , SR.TIP_MOV  , SR.DT_SYS  , SR.COMPANY , SR.X_FLG01 ,   
  SR.X_FLG02 , SR.X_FLG03  , SR.X_FLG04 , SR.X_FLG05 , SR.X_FLD01, SR.X_FLD02 , SR.X_FLD03, SR.X_FLD04 , SR.X_FLD05 
  )
WHEN NOT MATCHED THEN 
INSERT 
 (
  IDRECORD , PVE_SERV , DTOR_CLIE,  ORD_CLIEN , DDT_DATE , CLI_CONCE , DDT_NUM  , COD_ART ,  
  NUM_ROW  , QTA_ART  , REASON , YEAR_CONS , TIP_MOV  , DT_SYS  , COMPANY , X_FLG01 ,   
  X_FLG02 , X_FLG03  , X_FLG04 , X_FLG05 , X_FLD01, X_FLD02 , X_FLD03, X_FLD04 , X_FLD05 
  )
  VALUES 
  (
  SR.IDRECORD , SR.PVE_SERV , SR.DTOR_CLIE , SR.ORD_CLIEN, SR.DDT_DATE , SR.CLI_CONCE , SR.DDT_NUM  , SR.COD_ART ,  
  SR.NUM_ROW  , SR.QTA_ART  , SR.REASON , SR.YEAR_CONS , SR.TIP_MOV  , SR.DT_SYS  , SR.COMPANY , SR.X_FLG01 ,   
  SR.X_FLG02 , SR.X_FLG03  , SR.X_FLG04 , SR.X_FLG05 , SR.X_FLD01, SR.X_FLD02 , SR.X_FLD03, SR.X_FLD04 , SR.X_FLD05 
  ); 
