

SELECT * FROM smetstbnd.V5TDOC0F vtf 

WHERE  T劫DOC='OA' 
AND  T助SIN='SMEUPBND' 
AND  T別GIN='XNBI01'

DELETE FROM smetstbnd.V5TDOC0F vtf 
WHERE  T劫DOC='OA' 
AND  T助SIN='SMEUPBND' 
AND  T別GIN='XNBI01'

SELECT * FROM smetstbnd.V5RDOC0F vtf 
WHERE  R劫DOC='OA' 
AND  R助SIN='SMEUPBND' 
AND  R別GIN='XNBI01'

DELETE  FROM smetstbnd.V5RDOC0F vtf 
WHERE  R劫DOC='OA' 
AND  R助SIN='SMEUPBND' 
AND  R別GIN='XNBI01'

COMMIT 


SELECT 
TTELEM AS "ZONA", 
TTDESC AS "DESC", 
SUBSTR(TTUSER, 26, 3)  AS "MAGRIF", 
SUBSTR(TTUSER, 72, 4)  "ZONBND" 
FROM SMETSTBND.TABEL00F WHERE TTSETT='ZON'

select * from smetstbnd.tabeld0f where ttsett='MAG' 


SELECT * FROM SMEDATFDA.CｚONR0F 
WHERE CΛUMP='GC1'

SELECT * FROM SMEDATBND.TABEL00F tf 
WHERE TTSETT='XB*37'

SELECT * FROM SMEDATBND.CｚONR0F 
WHERE CΛUMP='X68'
--CΡPRC='X68'

INSERT INTO CED.CｚONR0F 
SELECT * FROM SMEDATBND.CｚONR0F 
WHERE CΛUMP='X68'

UPDATE  CED.CｚONR0F
SET CΛUMP='GC1', 
CΜRAG=114500, 
CΣSAG='EDP01', 
CΜGAG='EDPSQL'

INSERT INTO SMEDATBND.CｚONR0F SELECT * FROM CED.CｚONR0F


SELECT *  FROM NBFDATSTBN.XNBLOG0F

SELECT COUNT(*)  FROM NBFDATSTBN.XNBLOG0F 

SELECT DISTINCT e兌DRE  FROM NBFDATSTBN.XNBLOG0F

SELECT E兌DRE,e余RRO,e佝ILE  FROM NBFDATSTBN.XNBLOG0F 
WHERE E兌DRE IN (SELECT DISTINCT P.E兌DRE FROM NBFDATSTBN.XNBLOG0F P)
GROUP BY E兌DRE, E余RRO, "E佝ILE" 


SELECT * FROM SMEDATBND.CｚONR0F 
WHERE CΛUMP='X25'

SELECT CΡPRC,COUNT(CΡPRC) FROM SMEDATBND.CｚONR0F 
WHERE CΛUMP='X25'
GROUP BY CΡPRC

SELECT E低RAG,E刪AGS FROM SMEDATBND.BRENTI0F  
WHERE E低RAG NOT IN (
SELECT DISTINCT X.E低CON FROM SMEDATBND.BRENTI0F X 
WHERE X.E劫CON='CLI' AND X.E劫RAG='PVE' AND X.E低RAG IN 
(
SELECT DISTINCT TRIM(CｚD01) FROM SMEDATBND.CｚONR0F WHERE CΡPRC='PVE' AND CΛUMP='X25'
)
)






