
-- Esempio di lettura C5RATE0F 
-- V.L. C5RATE3L contiene solo le partite aperte 
SELECT S5CDOG,S5NDOR,S5DDOR,
S5CAUS,
(SELECT ttdesc FROM smedatbnd.tabel00f WHERE ttsett='C5V' AND ttelem =S5CAUS) AS casuale,
S5DAAV, -- S5IMPO,
CASE WHEN S5SCAD <= VARCHAR_FORMAT(CURRENT_DATE,'YYYYMMDD') THEN S5IMPO  ELSE 0 END AS SCADUTO,
CASE WHEN S5SCAD > VARCHAR_FORMAT(CURRENT_DATE,'YYYYMMDD')  THEN S5IMPO  ELSE 0 END AS ASCADERE,
S5IMPA  
FROM SMEDATBND.C5RATE3L                                            
WHERE S5TPOG = 'CNCLI'


SELECT * FROM SMEDATBND.C5RATE3L WHERE S5CAUS='500'



SELECT * FROM NBFDATBND.BSOSPESI0F  
WHERE UNSDEBTCOD IN (
SELECT DISTINCT S5IDOJ FROM SMEDATBND.C5RATE3L
)


SELECT * FROM NBFDAT.BSOSPESI0F  
WHERE UNSDEBTCOD IN (
SELECT DISTINCT S5IDOJ FROM SMEDATFDA.C5RATE3L
)



SELECT DISTINCT PDC FROM CED.SCART



-- TIPO PALLET PREFERITO 
SELECT * FROM SMEDATBND.C£CONR0F  WHERE C£TPRC='CLI' AND C£NUMP='X25' AND C£CD01 IN (

SELECT * FROM SMEDATBND.BRENTI0F B WHERE B.E§TRAG='CLI' AND 
B.E§DINV <= VARCHAR_FORMAT(CURRENT_DATE,'YYYYMMDD')     AND 
B.E§DFNV >= VARCHAR_FORMAT(CURRENT_DATE,'YYYYMMDD')     AND
B.E§CRAG IN (
'450204', '450206', '450333', '450420', '450431', '450532','450589','450653','450713','450772','450774','450788','450863','450953','450970',
'450980','450983','450994','451012','451026','451140','452524','452526','450602','902899','902891','450251','982880','453315','450621'
)


-- selezione elenco CLI attivi nella forma .compatta
SELECT * FROM SMEDATBND.BRENTI0F B WHERE  E§TRAG='CLI' AND 
B.E§DINV <= VARCHAR_FORMAT(CURRENT_DATE,'YYYYMMDD')    AND 
B.E§DFNV >= VARCHAR_FORMAT(CURRENT_DATE,'YYYYMMDD')


-- selezione elenco PVE attivi nella forma compatta
SELECT * FROM SMEDATBND.BRENTI0F B WHERE  E§TRAG='PVE' AND
B.E§DINV <= VARCHAR_FORMAT(CURRENT_DATE,'YYYYMMDD')    AND 
B.E§DFNV >= VARCHAR_FORMAT(CURRENT_DATE,'YYYYMMDD')


-- PRIMA QUERY 
SELECT  MAX(LEFT(T.TTUSER,3)) AS DISTRETTO, B.E§ZONA AS ZONA,T.TTDESC AS DESCRIZIONE, sum(S1.DARE) AS DARE, sum(S1.AVERE) AS AVERE, sum(S1.DARE)-sum(S1.AVERE) AS SALDO 
FROM (
SELECT
CASE WHEN S.UNSDOCTYPE IN('F', 'D') THEN S.UNSVALUE ELSE 0 END AS DARE,
CASE WHEN S.UNSDOCTYPE IN('P', 'A') THEN S.UNSVALUE ELSE 0 END AS AVERE, S.*
FROM NBFDATBND.BSOSPESI0F S
) AS S1
INNER JOIN SMEDATBND.BRENTI0F B ON (B.E§TRAG='PVE' AND B.E§CRAG=S1.UNSENTSHCD)
INNER JOIN SMEDATBND.TABEL00F T ON (T.TTSETT='ZON' AND T.TTELEM=B.E§ZONA) 
AND B.E§DINV <= VARCHAR_FORMAT(CURRENT_DATE,'YYYYMMDD') AND COALESCE(NULLIF(B.E§DFNV, 0),99999999) >= VARCHAR_FORMAT(CURRENT_DATE,'YYYYMMDD')
WHERE  1=1 
GROUP BY B.E§ZONA,T.TTDESC

-- Query 311 
-- Dettaglio Zona Incassi da Versare BINDI
SELECT max(S1.UNSENTBLCD) AS CLI, S1.UNSENTSHCD AS PVE, B.E§RAGS AS RAGIONESOCIALE, C.P£CDVA AS INSEGNA, B.E§ZONA AS ZONA, sum(S1.DARE) AS DARE, sum(S1.AVERE) AS AVERE, sum(S1.DARE)-sum(S1.AVERE) AS SALDO 
FROM (
SELECT
CASE WHEN S.UNSDOCTYPE IN('F', 'D') THEN S.UNSVALUE ELSE 0 END AS DARE,
CASE WHEN S.UNSDOCTYPE IN('P', 'A') THEN S.UNSVALUE ELSE 0 END AS AVERE, S.*
FROM NBFDATBND.BSOSPESI0F S
) AS S1
-- INNER JOIN SMEDATBND.BRENTI0F B ON (B.E§TRAG='PVE' AND B.E§TCON='CLI' AND B.E§CCON=S1.UNSENTBLCD)
INNER JOIN SMEDATBND.BRENTI0F B ON (B.E§TRAG='PVE' AND B.E§CRAG=S1.UNSENTSHCD)
INNER JOIN smedatbnd.c£eso00f C ON (B.E§TRAG='PVE' AND B.E§CRAG = C.P£CD01)
AND B.E§DINV <= VARCHAR_FORMAT(CURRENT_DATE,'YYYYMMDD') AND COALESCE(NULLIF(B.E§DFNV, 0),99999999) >= VARCHAR_FORMAT(CURRENT_DATE,'YYYYMMDD')
WHERE B.E§ZONA=#zonbnd#
AND LENGTH(TRIM(UNSDOCNUMB)) > 2
AND C.P£NUMP = 'D15'
GROUP BY S1.UNSENTSHCD, B.E§ZONA, B.E§RAGS, C.P£CDVA

-- Query 312 
-- Dettaglio fatture BINDI
WITH T1 AS (
SELECT 
CASE WHEN (TP = '0' AND TIPO <> 'DOCUMENTO') THEN '1' ELSE TP END AS TP,
TIPO,CLI,PVE,ZONA,DOCNUM,DOCDATA,DOCINFO,DARE,AVERE,
CASE WHEN (TP = '0' AND TIPO <> 'DOCUMENTO') THEN 0 ELSE saldo END AS SALDO, UNSDOVUCOD
FROM (
-- Testata
SELECT min(S1.TP) AS TP, 'DOCUMENTO' AS TIPO, max(S1.UNSENTBLCD) AS CLI, S1.UNSENTSHCD AS PVE, max(B.E§ZONA) AS ZONA, S1.UNSDOCNUMB AS DOCNUM,
max(S1.UNSDATAISS) AS DOCDATA, max(S1.DESCR) AS DOCINFO, sum(S1.DARE) AS DARE, sum(S1.AVERE) AS AVERE,
sum(S1.DARE) - sum(S1.AVERE) AS SALDO, MAX(S1.UNSDOVUCOD) AS UNSDOVUCOD
FROM 
(
	SELECT
	CASE WHEN S.UNSDOCTYPE IN('F', 'D') THEN '0' ELSE '0' END AS TP,
	CASE WHEN S.UNSDOCTYPE IN('F', 'D') THEN S.UNSNOTE ELSE '' END AS DESCR,
	CASE WHEN S.UNSDOCTYPE IN('F', 'D') THEN S.UNSVALUE ELSE 0 END AS DARE,
	CASE WHEN S.UNSDOCTYPE IN('P', 'A') THEN S.UNSVALUE ELSE 0 END AS AVERE, S.*
	FROM NBFDATBND.BSOSPESI0F S
) AS S1
INNER JOIN SMEDATBND.BRENTI0F B ON (B.E§TRAG='PVE' AND B.E§CRAG=S1.UNSENTSHCD)
AND B.E§DINV <= VARCHAR_FORMAT(CURRENT_DATE,'YYYYMMDD') AND COALESCE(NULLIF(B.E§DFNV, 0),99999999) >= VARCHAR_FORMAT(CURRENT_DATE,'YYYYMMDD')
WHERE S1.UNSENTBLCD=#clibnd#
-- WHERE S1.UNSENTBLCD='528539'
GROUP BY S1.UNSENTSHCD, S1.UNSDOCNUMB
UNION
-- Righe
SELECT S1.TP, '' AS TIPO, S1.UNSENTBLCD AS CLI, S1.UNSENTSHCD AS PVE, B.E§ZONA AS ZONA, S1.UNSDOCNUMB AS DOCNUM, 
S1.UNSDATAMOV AS DOCDATA, S1.UNSNOTE AS DOCINFO, S1.DARE AS DARE, S1.AVERE AS AVERE,
CASE WHEN(S1.DARE = 0) THEN 0 ELSE S1.DARE - S1.AVERE END AS SALDO, 
UNSDOVUCOD
FROM 
(
	SELECT
	CASE WHEN S.UNSDOCTYPE IN('F', 'D') THEN '0' ELSE '1' END AS TP,
	CASE WHEN S.UNSDOCTYPE IN('F', 'D') THEN S.UNSVALUE ELSE 0 END AS DARE,
	CASE WHEN S.UNSDOCTYPE IN('P', 'A') THEN S.UNSVALUE ELSE 0 END AS AVERE, S.*
	FROM NBFDATBND.BSOSPESI0F S
) AS S1
INNER JOIN SMEDATBND.BRENTI0F B ON (B.E§TRAG='PVE' AND B.E§CRAG=S1.UNSENTSHCD)
AND B.E§DINV <= VARCHAR_FORMAT(CURRENT_DATE,'YYYYMMDD') AND COALESCE(NULLIF(B.E§DFNV, 0),99999999) >= VARCHAR_FORMAT(CURRENT_DATE,'YYYYMMDD')
WHERE S1.UNSENTBLCD=#clibnd#
-- WHERE S1.UNSENTBLCD='528539'
AND S1.AVERE>=0
) AS T2
)
SELECT TP,TIPO,CLI,SOSPESI.PVE,TRIM(E§RAGS) AS RAGIONESOCIALE,TRIM(INSEGNA) AS INSEGNA,ZONA,DOCNUM,DOCDATA,DOCINFO,
CAST(DARE AS DECIMAL(31,2)) AS DARE, CAST(AVERE AS DECIMAL(31,2)) AS AVERE,SALDO 
FROM (
SELECT * FROM T1
UNION
SELECT MAX('SALDO') AS TP, MAX('') AS TIPO, '' AS CLI, MAX('') AS PVE, MAX('') AS ZONA, MAX(' ') AS DOCNUM, MAX('') AS DOCDATA,
MAX('') AS DOCINFO, MAX(0) AS DARE, MAX(0) AS AVERE, SUM(SALDO) AS SALDO, MAX(UNSDOVUCOD) AS UNSDOVUCOD
FROM T1
WHERE LENGTH(TRIM(DOCNUM)) > 2
GROUP BY CLI
) SOSPESI
LEFT JOIN SMEDATBND.BRENTI0F S ON (E§TRAG='PVE' AND S.E§CRAG=SOSPESI.PVE) 
AND S.E§DINV <= VARCHAR_FORMAT(CURRENT_DATE,'YYYYMMDD') AND COALESCE(NULLIF(S.E§DFNV, 0),99999999) >= VARCHAR_FORMAT(CURRENT_DATE,'YYYYMMDD')
LEFT JOIN 
(
	SELECT TRIM(P£CD01) AS PVE,
	MAX(CASE WHEN P£NUMP='D15' THEN TRIM(P£CDVA) ELSE '' END) AS INSEGNA
	FROM SMEDATBND.C£ESO00F
	WHERE P£TPRC='PVE'
	GROUP BY P£CD01
) INSEGNA ON SOSPESI.PVE = INSEGNA.PVE
ORDER BY CASE WHEN DOCNUM = '' THEN null ELSE DOCNUM END, TIPO DESC, UNSDOVUCOD ASC, DARE DESC, DOCDATA
