


SELECT * FROM  smesys.USERLIST u 

LABEL ON COLUMN SMESYS.USERLIST( 
UPDCEN      TEXT IS 'Secolo di visualizzazione: 0-19xx, 1-20xx        ',
UPDDAT      TEXT IS 'Data di visualizzazione: AAMMGG                  ',
UPDTIM      TEXT IS 'Ora di visualizzazione                           ',
UPSYST      TEXT IS 'Sistema                                          ',
UPUPRF      TEXT IS 'Nome profilo utente                              ',
UPUSCL      TEXT IS 'Classe dell  utente                              ',
UPDSIN      TEXT IS 'Visualizzazione informazioni di collegamento     ',
UPPWCC      TEXT IS 'Secolo di modifica parola d ordine: 0-19xx, 1-20x',
UPPWCD      TEXT IS 'Data di modifica della parola d ordine: AAMMGG   ',
UPPWCT      TEXT IS 'Ora di modifica della parola d ordine            ',
UPPWEI      TEXT IS 'Intervallo di scadenza della parola d ordine     ',
UPPWEX      TEXT IS 'Parola d ordine impostata su Scaduta dal comando ',
UPPWON      TEXT IS 'La parola d ordine è *NONE: *YES o *NO           ',
UPPSOC      TEXT IS 'Secolo collegamento precedente: 0-19xx, 1-20xx   ',
UPPSOD      TEXT IS 'Data precedente collegamento: AAMMGG             ',
UPPSOT      TEXT IS 'Ora precedente collegamento                      ',
UPNVSA      TEXT IS 'Verifiche non valide                             ',
UPLDVS      TEXT IS 'Limite sessioni di unità                         ',
UPSPAU      TEXT IS 'Autorizzazioni speciali                          ',
UPMXST      TEXT IS 'Memoria massima                                  ',
UPMXSU      TEXT IS 'Memoria utilizzata                               ',
UPPRLT      TEXT IS 'Limite priorità                                  ',
UPINPG      TEXT IS 'Programma iniziale                               ',
UPINPL      TEXT IS 'Libreria del programma iniziale                  ',
UPJBDS      TEXT IS 'Descrizione lavoro                               ',
UPJBDL      TEXT IS 'Libreria della descrizione lavoro                ',
UPOWNR      TEXT IS 'Proprietario                                     ',
UPGRPF      TEXT IS 'Profilo di gruppo                                ',
UPGRAU      TEXT IS 'Autorizzazione del gruppo                        ',
UPGRPI      TEXT IS 'Indicatore profilo di gruppo: *YES o *NO         ',
UPACCD      TEXT IS 'Codice account                                   ',
UPMGQU      TEXT IS 'Coda messaggi                                    ',
UPMGQL      TEXT IS 'Libreria della coda messaggi                     ',
UPOTQU      TEXT IS 'Coda di emissione                                ',
UPOTQL      TEXT IS 'Libreria della coda di emissione                 ',
UPTEXT      TEXT IS 'Descrizione testuale                             ',
UPSPEN      TEXT IS 'Ambiente speciale                                ',
UPCRLB      TEXT IS 'Libreria corrente                                ',
UPINMN      TEXT IS 'Menu iniziale                                    ',
UPINML      TEXT IS 'Libreria del menu iniziale                       ',
UPLTCP      TEXT IS 'Capacità limitata                                ',
UPDLVY      TEXT IS 'Consegna a coda messaggi                         ',
UPSVRT      TEXT IS 'Gravità coda messaggi                            ',
UPPRDV      TEXT IS 'Unità di stampa                                  ',
UPATPG      TEXT IS 'Programma di attenzione                          ',
UPATPL      TEXT IS 'Libreria del programma di attenzione             ',
UPUSOP      TEXT IS 'Opzioni utente                                   ',
UPUPLK      TEXT IS 'Profilo utente bloccato                          ',
UPUPDM      TEXT IS 'Profilo utente danneggiato                       ',
UPSTAT      TEXT IS 'Stato                                            ',
UPKBDB      TEXT IS 'Memorizzazione in buffer tastiera                ',
UPASTL      TEXT IS 'Livello di assistenza                            ',
UPLANG      TEXT IS 'Identificativo lingua                            ',
UPCNTR      TEXT IS 'Identificativo regione                           ',
UPCCSI      TEXT IS 'Identificat. serie caratteri codificati (o CCSID)',
UPSRT       TEXT IS 'Sequenza di ordinamento                          ',
UPSRTL      TEXT IS 'Libreria della sequenza di ordinamento           ',
UPOBJA      TEXT IS 'Valore di controllo oggetto                      ',
UPAUDL      TEXT IS 'Valore di controllo azione                       ',
UPGATY      TEXT IS 'Tipo autorizzazione gruppo                       ',
UPSUPG      TEXT IS 'Gruppi supplementari                             ',
UPUID       TEXT IS 'Numero ID utente                                 ',
UPGID       TEXT IS 'Numero ID gruppo                                 ',
UPSETJ      TEXT IS 'Attributi lavoro locale                          ',
UPCHID      TEXT IS 'Controllo identificativo carattere               ',
UPENPW      TEXT IS 'Parola d ordine presente per livello 0 o 1       ',
UPENPH      TEXT IS 'Parola d ordine presente per livello 2 o 3       ',
UPENLM      TEXT IS 'Parola d ordine NetServer presente               ',
UPLPWM      TEXT IS 'Gestione parola d ordine locale                  ',
UPPWCB      TEXT IS 'Blocco modifica parola d ordine                  ',
UPPWDY      TEXT IS 'Giorni mancanti alla scadenza della p. d ordine  ',
UPEXPC      TEXT IS 'Secolo di scadenza parola d ordine: 0-19xx, 1-20x',
UPEXPD      TEXT IS 'Data scadenza parola d ordine: AAMMGG            ',
UPCRTC      TEXT IS 'Secolo di creazione: 0-19xx, 1-20xx              ',
UPCRTD      TEXT IS 'Data di creazione: AAMMGG                        ',
UPCRTT      TEXT IS 'Ora di creazione                                 ',
UPCHGC      TEXT IS 'Secolo di modifica: 0-19xx, 1-20xx               ',
UPCHGD      TEXT IS 'Data di modifica: AAMMGG                         ',
UPCHGT      TEXT IS 'Ora di modifica                                  ',
UPLSTC      TEXT IS 'Secolo ultimo utilizzo: 0-19xx, 1-20xx           ',
UPLSTD      TEXT IS 'Data ultimo utilizzo: AAMMGG                     ',
UPRSTC      TEXT IS 'Secolo di ripristino: 0-19xx, 1-20xx             ',
UPRSTD      TEXT IS 'Data di ripristino: AAMMGG                       ',
UPRSTT      TEXT IS 'Ora di ripristino                                ',
UPUENT      TEXT IS 'Titolarità utente richiesta                      ',
UPUEXC      TEXT IS 'Secolo di scadenza utente: 0-19xx, 1-20xx        ',
UPUEXD      TEXT IS 'Data di scadenza utente: AAMMGG                  ',
UPEXPI      TEXT IS 'Intervallo di scadenza utente                    ',
UPEXPA      TEXT IS 'Azione di scadenza utente                        ',
UPMXSTL     TEXT IS 'Memoria massima estesa                           ',
UPMXSUL     TEXT IS 'Memoria utilizzata estesa                        ',
UPCRTBY     TEXT IS 'Creato dall utente                               ',
UPAUTCOL    TEXT IS 'Raccolta autorizzazioni attiva: 0=No, 1=Sì       ',
UPAUTCOLEX  TEXT IS 'Contenitore raccolte autorizzaz. esiste: 0=N,1=S '
);

