

UPDATE SMEDATBND.BRENTI0F 
SET E§COD8='DET' 
WHERE (E§COD8='000' OR E§COD8='' ) 
AND E§TRAG='PVE' 
AND E§DINV <  VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD') 
AND E§DFNV >= VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD')
AND E§CRAG IN ( 
SELECT TRIM(digits(cdpve)) FROM ced.cdpve
)



-- VERIFICA CANALE DI VENDITA SUI PVE SERVITI DALLE ZONE DI CUI SOPRA
WITH X AS (
SELECT E§TRAG, E§NMNE, E§STAT, E§CRAG, E§RAGS, E§ZONA, E§COD1, E§COD8, E§TCON, E§CCON  
FROM SMEDATBND.BRENTI0F  WHERE E§TRAG='PVE'  
AND E§DINV <  VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD') 
AND E§DFNV >= VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD')
AND E§ZONA IN 
--('C02', 'S00', 'S01', 'S02', 'S03', 'S04', 'S05', 'S06', 'S07', 'S08', 'S09', 'S10', 'S11', 'C05', 'L08', 'L10', 'L11', 'L09', 'A02', 'P01', 'P02', 'P03', 'P04', 'P08', 'P09' )
('B01', 'B02', 'B03', 'B04', 'B05', 'B06', 'B07')
), Y AS (
SELECT E§TRAG, E§CRAG,E§NMNE,E§STAT,E§RAGS FROM SMEDATBND.BRENTI0F  
WHERE
    E§DINV <  VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD') 
AND E§DFNV >= VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD')
)
SELECT  
/*x.E§TCON AS "Tipo   CLI",*/
x.E§CCON AS "Codice CLI;CNCLI",
y.E§NMNE AS "Sigla  CLI",
y.E§STAT AS "Stato  CLI",
y.E§RAGS AS "Ragione Sociale CLI",
/*x.E§TRAG AS "Tipo   PVE",*/
x.E§CRAG AS "Codice PVE;CNPVE",
x.E§NMNE AS "Sigla  PVE",
x.E§STAT AS "Stato  PVE",
x.E§RAGS AS "Ragione Sociale PVE",
x.E§ZONA AS "Zona", 
x.E§COD1 AS "Magazzino",
x.E§COD8 AS "Canale di Vendita"
FROM X,Y WHERE x.E§TCON=y.E§TRAG AND x.E§CCON=y.E§CRAG  
ORDER BY
/*"Tipo   CLI",*/
"Stato  CLI","Codice CLI;CNCLI" 
