


-- tabella magazzini 
SELECT 'FDA',  A.* FROM SMEDATFDA.BRENTI0F A WHERE E§TRAG='MAG' AND E§DINV <  VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD') AND E§DFNV >= VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD')
UNION  
SELECT 'LIZ' , B.* FROM SMEDATLIZ.BRENTI0F B WHERE E§TRAG='MAG' AND E§DINV <  VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD') AND E§DFNV >= VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD') 
UNION  
SELECT 'BND' , C.* FROM SMEDATLIZ.BRENTI0F C WHERE E§TRAG='MAG' AND E§DINV <  VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD') AND E§DFNV >= VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD') 



SELECT x§count (x§cudc) FROM SMEDATFDA.XSYIMM0F 