

INSERT INTO CED.GMFOTO0F 
SELECT * FROM SMEDATFDA.GMFOTO0F gf  
WHERE J兌DEN='GC' AND J劫IGC='10' ORDER BY  J你RTI , J伶ATA


DELETE  FROM ced.gmfoto0f WHERE left("J伶ATA",4)=2023

SELECT SUBSTR(J伶ATA, 5, 2) FROM SMEDATFDA.GMFOTO0F 
WHERE J兌DEN='GC'

SELECT J伶ATA, J你RTI, SUBSTR(J伶ATA, 5,2), SUM(J利TGZ) FROM ced.GMFOTO0F gf   
GROUP BY J伶ATA, J你RTI 
ORDER BY J你RTI,J伶ATA

DROP TABLE ced.artwkgia

CREATE TABLE CED.ARTWKGIA (DTDOM CHAR(8), ART CHAR(15), MESE CHAR(2), QTDOM DEC(10, 3))

INSERT INTO CED.ARTWKGIA 
SELECT J伶ATA, J你RTI, SUBSTR(J伶ATA, 5,2), SUM(J利TGZ) FROM ced.GMFOTO0F gf   
GROUP BY J伶ATA, J你RTI 
ORDER BY J你RTI,J伶ATA


SELECT art, count(art) FROM CED.ARTWKGIA  WHERE count(art) = 52  

SELECT * FROM ced.artwkgia WHERE art=3012982

DROP TABLE QTEMP.GMART 

CREATE TABLE QTEMP.GMART (ART CHAR(15), MESE CHAR(2) , NWK CHAR(2),  TOTM DEC(10,3), GGM DEC(10, 0))


INSERT INTO  QTEMP.GMART 
SELECT ART,  MESE, COUNT(MESE) AS NWK, SUM(QTDOM) AS TOTM,    SUM(QTDOM)/COUNT(MESE)  AS GGM FROM CED.ARTWKGIA  --WHERE TOTM
GROUP BY ART,MESE 
ORDER BY ART,MESE  

SELECT * FROM QTEMP.GMART 

SELECT ART, SUM(TOTM), COUNT(ART), SUM(TOTM)/COUNT(ART) FROM QTEMP.GMART 
GROUP BY ART


