SELECT CONNECTION_TYPE,
       CONNECTION_OPEN_TYPE,
       BIND_USER,
       IDLE_TIME,
       BYTES_RECEIVED_LOCALLY,
       BYTES_SENT_REMOTELY,
       CASE
           WHEN TCP_STATE IS NULL
               AND PROTOCOL = 'UDP' THEN '*UDP'
           ELSE TCP_STATE
       END AS TCP_STATE,
       CASE REMOTE_PORT
           WHEN '0' THEN '*'
           ELSE CHAR(REMOTE_PORT)
       END AS REMOTE_PORT,
       CASE REMOTE_ADDRESS
           WHEN '0.0.0.0' THEN '*'
           WHEN '0' THEN '*'
           WHEN '::' THEN '*'
           ELSE REMOTE_ADDRESS
       END AS REMOTE_ADDRESS,
       CASE LOCAL_PORT
           WHEN '0' THEN '*'
           ELSE CHAR(LOCAL_PORT)
       END AS LOCAL_PORT,
       CASE LOCAL_ADDRESS
           WHEN '0.0.0.0' THEN '*'
           WHEN '::' THEN '*'
           ELSE LOCAL_ADDRESS
       END AS LOCAL_ADDRESS
    FROM QSYS2.NETSTAT_INFO 
    WHERE CONNECTION_TYPE = 'IPV4' 
    --AND REMOTE_ADDRESS = '192.168.240.1'   -- replica bindi 
    --AND REMOTE_ADDRESS = '192.9.207.200'   -- replica dep S4 cagliari 
    --AND REMOTE_ADDRESS = '192.168.240.40'   -- globe bindi  
    
    
    
    WITH X AS (
    SELECT C£TPRC,C£CD01,C£NUMP,C£CDVA  FROM smedatbnd.c£conr0f WHERE c£nump='X24' 
    AND c£tprc='PVE' --AND c£cd01 IN ('118489', '118490', '118491') 
    AND C£CD01 IN (SELECT E§CRAG FROM SMEDATBND.BRENTI0F WHERE E§TRAG='PVE' AND E§CCON IN ('118489', '118490', '118491')  )
    ) 
    SELECT X.*, E§CCON FROM SMEDATBND.BRENTI0F 
    WHERE E§
    
    
   SELECT T§CDMG AS 'MAG', T§ZONA AS 'ZONA', T§CDVG AS 'VIAGGIO',  T§VET1 AS 'VETTORE', T§RVE1 AS 'DES.VETTORE' 
   FROM SMEDATBND.V5TDOC0L  WHERE T§TDOC=[TIPO DOCUMENTO] 
   AND T§NDOC=[NUMERO INTERNO DOCUMENTO]