

SELECT OBJECT_NAME(OBJECT_ID) AS DatabaseName,
 last_user_update,*
FROM sys.dm_db_index_usage_stats
WHERE database_id = DB_ID( 'AXIB') 
AND (
OBJECT_NAME(OBJECT_ID) like '%EDO%' 
OR 
OBJECT_NAME(OBJECT_ID) like '%SMEUP%' 
)

SELECT OBJECT_NAME(OBJECT_ID) AS DatabaseName, last_user_update,*
FROM sys.dm_db_index_usage_stats
WHERE database_id = DB_ID( 'AXIB') AND OBJECT_NAME(OBJECT_ID) like 'Edo_ESTR_%_SMEUP'


select * from smedatbnd.tabel00f 
where ttsett='ZON' 


select e§cod5 , e§fl36 from SMEDATBND.brenti0f where e§cpai='12580001001'



CREATE TABLE BINDIGEST.dbo.PV_EXE_0007_TblDecZon (
	ZONBND nvarchar(5) COLLATE Latin1_General_CI_AS NOT NULL,
	ZONSME nvarchar(3) COLLATE Latin1_General_CI_AS NOT NULL,
	CRDZON int ,
	DT_SYS datetime DEFAULT getdate() NULL,
	COMPANY nvarchar(50) COLLATE Latin1_General_CI_AS NULL
);

DROP TABLE BINDIGEST.dbo.PV_EXE_0007_TblDecZon;

insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A423','A00');

insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A514','A01');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A515','A02');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A516','A03');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A520','A04');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A523','A05');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A524','A06');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A525','A07');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A526','A08');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A528','A09');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A529','A10');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A531','A11');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A532','A12');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A535','A13');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A536','A14');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A537','A15');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A538','A16');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A540','A17');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A521','A18');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A591','A19');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A998','A20');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A576','A21');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A578','B00');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A572','B01');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A573','B02');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A574','B03');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A575','B04');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('A576','B05');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES(' L50','L00');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES(' L50','L01');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES(' L50','L02');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES(' L50','L03');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES(' L50','L04');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES(' L50','L05');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES(' L50','L06');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES(' LNE','L07');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('L520','L08');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('L521','L09');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('L522','L10');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('L523','L11');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('P501','P01');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('P502','P02');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('P503','P03');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('TIBA','P04');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('P508','P08');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('P509','P09');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('Z524','Z01');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('Z525','Z02');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('Z526','Z03');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('Z527','Z04');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('Z528','Z05');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('Z530','Z06');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('Z533','Z07');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('Z536','Z08');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('Z537','Z09');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('Z538','Z10');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('Z539','Z11');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('Z542','Z12');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('Z544','Z13');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('Z545','Z14');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('Z546','Z15');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('Z531','Z16');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('Z543','Z17');
insert INTO BINDIGEST.dbo.PV_EXE_0007_TblDecZon(ZONBND,ZONSME)	VALUES('Z998','Z18');

UPDATE BINDIGEST.dbo.PV_EXE_0007_TblDecZon 
SET COMPANY='10'