WITH X AS ( SELECT '10' AS K01, 'NIL' "K03", 'NIL' AS "K04", 'NIL' AS "K51", 'NIL' "NR.DDT",
T§CORD AS K05, '-' AS K06, 'NIL' K07,'NIL' K08,
'NIL' "TIPO DOC.INTERNO", 'NIL' "NR.DOC.INTERNO", '-' AS K09, T§CODF "K10", 'NIL' "K31", 'NIL' "K11", 'NIL' AS K12, 'NIL' AS K12E, 'NIL' AS K13, '-' AS K14, 'NIL' AS K15,
'NIL' K16, 'NIL' K17, 'NIL' K18, 'NIL' K19, 'NIL' K20,'NIL' K21,'NIL' K22,'NIL' K23, A.E§CTA1 K24,'NIL' K25,'NIL' K26,'NIL' K27,'NIL' K28,'NIL' K29,'NIL' K30,
'NIL' AS  "DATA DOC.INTERNO",
'NIL' AS "DATA DDT",
'NIL' "TIPO ENTE DEST.", 'NIL' "K48", 'NIL' "SIGLA PVE", 'NIL' "K49",
'NIL' "TIPO ENTE FATT.", 
'NIL' "K32", 'NIL' "K33", 'NIL' "K38", 'NIL' "K39",
'NIL' "K46", 'NIL' "K47",
CASE B.E§COD9 WHEN 'FDA' THEN 'FORNO D''ASOLO' WHEN 'DON' THEN 'LA DONATELLA' ELSE 'SIPA SPA' END K58, T§FL13 AS FL13, T§FL19 AS FL19
FROM SMEDATBND.V5TDOC0F,
SMEDATBND.BRENTI0F A,
SMEDATBND.BRENTI0F B,
SMEDATBND.BRENTI0F C,
SMEDATBND.TABEL00F
WHERE T§TDOC = 'DA' AND  T§NFAT= 'A823000225' AND T§DFAT BETWEEN 20231231 AND 20231231 AND T§STAT < '90' AND
 A.E§TRAG = T§TCDF AND A.E§CRAG = T§CODF AND
 A.E§DINV <= YEAR(CURRENT_DATE)*10000 + MONTH(CURRENT_DATE)*100 + DAY(CURRENT_DATE) AND
 A.E§DFNV >= YEAR(CURRENT_DATE)*10000 + MONTH(CURRENT_DATE)*100 + DAY(CURRENT_DATE) AND
 B.E§TRAG = T§TCCL AND B.E§CRAG = T§CDCL AND
 B.E§DINV <= YEAR(CURRENT_DATE)*10000 + MONTH(CURRENT_DATE)*100 + DAY(CURRENT_DATE) AND
 B.E§DFNV >= YEAR(CURRENT_DATE)*10000 + MONTH(CURRENT_DATE)*100 + DAY(CURRENT_DATE) AND
    C.E§TRAG = 'MAG' AND C.E§CRAG = T§CDMG AND
C.E§DINV <= YEAR(CURRENT_DATE)*10000 + MONTH(CURRENT_DATE)*100 + DAY(CURRENT_DATE) AND
     C.E§DFNV >= YEAR(CURRENT_DATE)*10000 + MONTH(CURRENT_DATE)*100 + DAY(CURRENT_DATE) AND
     TTSETT = 'ZON' AND TTELEM = CASE T§ZONA WHEN '' THEN 'AAA' ELSE T§ZONA END )
SELECT X.*, TTDESC AS K02 FROM X LEFT JOIN SMEDATBND.TABEL00F P ON P.TTELEM = X.FL13
 WHERE P.TTSETT= 'XB*80'