

WITH T1 AS (
SELECT
A你RTI AS CART,
--CASE WHEN A低OD1='' THEN '-' ELSE A低OD1 END AS CD1,
A低OD1 AS CD1,
-- COALESCE(NULLIF(A低OD1, ''), '-') AS CD1,
CONCAT(CONCAT(TRIM(A低OD1), '-'), TRIM(A低OD2)) AS CD12,
CONCAT(CONCAT(CONCAT(TRIM(A低OD1), '-'), CONCAT(TRIM(A低OD2),'-')),TRIM(A低OD3)) AS CD123,
CONCAT(CONCAT(CONCAT(CONCAT(TRIM(A低OD1), '-'), CONCAT(TRIM(A低OD2),'-')),CONCAT(TRIM(A低OD3),'-')),TRIM(A低OD4)) AS CD1234
FROM SMEDATBND.BRARTI0F bf WHERE A刨TAT='10' AND A劫PAR='1' AND A劫IAR='F' AND A低OD1<>''
)
SELECT T1.CART,L.*
FROM SMEDATBND.CΙIST0F AS L
INNER JOIN T1 ON T1.CD1=L.L低OD2
WHERE L.L低DLI='BND' AND L.L低DSL='BND'
AND L.L低OD1 IN ('C2','NET. CES. CONC.','02NEW','900006')
UNION
SELECT T1.CART,L.*
FROM SMEDATBND.CΙIST0F AS L
INNER JOIN T1 ON T1.CD12=L.L低OD2
WHERE L.L低DLI='BND' AND L.L低DSL='BND'
AND L.L低OD1 IN ('C2','NET. CES. CONC.','02NEW','900006')
UNION
SELECT T1.CART,L.*
FROM SMEDATBND.CΙIST0F AS L
INNER JOIN T1 ON T1.CD123=L.L低OD2
WHERE L.L低DLI='BND' AND L.L低DSL='BND'
AND L.L低OD1 IN ('C2','NET. CES. CONC.','02NEW','900006')
UNION
SELECT T1.CART,L.*
FROM SMEDATBND.CΙIST0F AS L
INNER JOIN T1 ON T1.CD1234=L.L低OD2
WHERE L.L低DLI='BND' AND L.L低DSL='BND'
AND L.L低OD1 IN ('C2','NET. CES. CONC.','02NEW','900006')
