

-- ESTRAZIONE ELENCO DEI CLIENTI BLOCCATI IN SEGUITO AI NUOVI VALORI SOGLIA IMPOSTATI
-- L'ELENCO RIPORTA L'ENTE CLI CON RELATIVO STATO, L'ENTE PVE DI RIFERIMENTO, CON STATO, ZONA E MAGAZZINO DI SERVIZIO  
WITH M AS (
SELECT E§CRAG AS CDPVE,
E§STAT AS STPVE,
E§NMNE AS SIGPVE,
E§RAGS AS RAGPVE, 
E§COD1 AS MAGPVE,
E§ZONA AS ZONPVE,
(SELECT SUBSTRING(TTUSER, 11, 3)  FROM SMETSTBND.TABEL00F WHERE TTSETT='ZON' AND TTELEM=E§ZONA) AS GGZONBLOC,
(SELECT P£CDVA FROM SMETSTBND.C£ESO00F WHERE P£NUMP='D15' AND P£CD01=E§CRAG) AS INSPVE
FROM SMETSTBND.BRENTI0F 
WHERE E§TRAG='PVE' 
AND E§DINV <  VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD') 
AND E§DFNV >= VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD')
)
SELECT  INT(XCGG01) AS GGSCAD, 
(
(SELECT COALESCE(SUM(S5IMPO-S5IMPA),0) FROM SMETSTBND.C5RATE3L 
WHERE S5TPOG = 'CNCLI' AND S5AZIE='10' AND S5CDOG=E§CRAG AND S5DAAV = 'D' AND S5SCAD <= VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD')) 
-
(SELECT COALESCE(SUM(S5IMPO-S5IMPA),0) FROM SMETSTBND.C5RATE3L 
WHERE S5TPOG = 'CNCLI' AND S5AZIE='10' AND S5CDOG=E§CRAG AND S5DAAV = 'A' AND S5SCAD <= VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD'))
) AS SCADUTO,
E§CRAG AS CDCLI, E§STAT AS STATOCLI, E§NUM3 AS GGCLIBLOC,  
(SELECT C£CDVA FROM SMETSTBND.C£CONR0F WHERE C£TPRC='CLI' AND C£NUMP='X14' AND C£CD01=E§CRAG) AS GRPCLI,
E§CCRR AS PVERIF, M.*
FROM SMETSTBND.BRENTI0F INNER JOIN M ON E§CCRR=CDPVE
INNER JOIN SMETSTBND.XC5BLO0F ON E§CRAG=XCCDOG 
WHERE E§TRAG='CLI' AND E§DINV < VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD')  AND E§DFNV >= VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD')
ORDER BY MAGPVE,ZONPVE 


SELECT COALESCE(SUM(S5IMPO-S5IMPA),0) FROM SMETSTBND.C5RATE3L 
WHERE S5TPOG = 'CNCLI' AND S5CDOG='450037' AND S5DAAV = 'D' AND S5SCAD <= VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD') 

-

SELECT COALESCE(SUM(S5IMPO-S5IMPA),0) FROM SMETSTBND.C5RATE3L 
WHERE S5TPOG = 'CNCLI' AND S5CDOG='450037' AND S5DAAV = 'A' AND S5SCAD <= VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD')

