

gmrrim0f set r£qeui=r£qrui, r£qeuc=r£qruc , r£live='8',   
-- r£stat='80  where


SELECT * FROM SMETSTBND.GMRRIM0F 
WHERE R£USAG='F3USR1' AND 
R£DTAG=20230207 

SELECT * FROM SMETSTBND.GMTRIM0F 
WHERE T£USAG='F3USR1' AND T£CDMG='F3' 
AND T£NRDM IN (
SELECT DISTINCT(R£NRDM) FROM SMETSTBND.GMRRIM0F 
WHERE R£USAG='F3USR1' AND 
R£DTAG=20230207
)

SELECT * FROM SMETSTBND.V5TRIP0F 

WHERE V$USAG='F3USR1' AND V$DTAG=20230207 

DELETE FROM SMETSTBND.V5TRIP0F 
WHERE V$USAG='F3USR1' AND V$DTAG=20230207 

DELETE  FROM SMETSTBND.GMTRIM0F 
WHERE T£USAG='F3USR1' AND T£CDMG='F3' 
AND T£NRDM IN (
SELECT DISTINCT(R£NRDM) FROM SMETSTBND.GMRRIM0F 
WHERE R£USAG='F3USR1' AND 
R£DTAG=20230207
) 

DELETE FROM SMETSTBND.GMRRIM0F 
WHERE R£USAG='F3USR1' AND 
R£DTAG=20230207

COMMIT

SELECT * FROM SMETSTBND.V5TDOC0F  
WHERE   T§TDOC IN ('OA', 'DA') 
AND T§DTIN>=20230321 AND T§OGAG='XNBI01'

DELETE  FROM SMETSTBND.V5TDOC0F  
WHERE   T§TDOC IN ('OA', 'DA') 
AND T§DTIN>=20230321 AND T§OGAG='XNBI01'

SELECT * FROM SMETSTBND.V5RDOC0F  
WHERE   R§TDOC IN ('OA', 'DA') 
AND R§DTIN>=20230321 AND R§OGAG='XNBI01' 

DELETE  FROM SMETSTBND.V5RDOC0F  
WHERE   R§TDOC IN ('OA', 'DA') 
AND R§DTIN>=20230321 AND R§OGAG='XNBI01' 





DELETE  FROM SMETSTBND.V5RDOC0F  
WHERE   R§TDOC IN ('OA', 'DA') 
AND R§DTIN>=20230206 

DELETE  FROM SMETSTBND.V5TDOC0F  
WHERE   T§TDOC IN ('OA', 'DA') 
AND T§DTIN>=20230206 

SELECT * FROM SMETSTBND.V5TDOC0F 


SELECT * FROM NBFDATSTBN.IDOCLINE

SELECT * FROM NBFDATSTBN.IDOCHEADER


DELETE FROM NBFDATSTBN.IDOCHEADER 
WHERE DCHORDCODE <>'C238213A5355K0nqM3G'

DELETE  FROM NBFDATSTBN.IDOCLINE
WHERE DCLORDCODE <>'C238213A5355K0nqM3G'


INSERT INTO NBFDATSTBN.IDOCHEADER SELECT * FROM CED.IDOCHEADER 

INSERT INTO NBFDATSTBN.IDOCLINE SELECT * FROM CED.IDOCLINE 

SELECT count(*) FROM SMEDATBND.GMQUAN0F

SELECT e§trag,e§zona, e§crag,e§rags FROM smetstbnd.brenti0f 
WHERE e§trag='CLI' AND e§crag IN (
SELECT DISTINCT t§codf FROM smetstbnd.V5TDOC0F vtf 
WHERE t§tdoc='OA'
)

SELECT count(*) FROM SMETSTBND.GMQUAN0F 

SELECT * FROM smetstbnd.v5tdoc0f  

INSERT INTO SMETSTBND.BRENTI0F 
SELECT * FROM smedatfda.brenti0f WHERE e§trag='VET' 
AND e§crag LIKE 'MT%' 

COMMIT

SELECT * FROM SMETSTBND.BRENTI0F bf 
WHERE E§TRAG='VET' AND E§CRAG LIKE 'MT%'

SELECT E§TRAG,E§CRAG,E§NMNE, E§RAGS, E§ZONA, E§STAT, E§COD1 FROM SMETSTBND.BRENTI0F 
WHERE E§TRAG='PVE' AND E§NMNE IN (
SELECT DISTINCT H§CDCL FROM NBFDATSTBN.XNBIHE0F 
WHERE H§CDMG=''
)


SELECT T§DTRI,T§DTCO,T§COD3, T§DTIN,T§USIN,T§OGAG  FROM SMETSTBND.V5TDOC0F 
WHERE T§DTIN=20230321 AND T§USIN ='SMEUPBND'


INSERT INTO smetstbnd.gmquan0f 
SELECT * FROM smeDATbnd.gmquan0f 

SELECT * FROM SMETSTBND.GMQUAN0F  


SELECT * FROM SMETSTBND.GMTRIM0F WHERE T£CDMG NOT IN ('F1')

DELETE  FROM SMETSTBND.GMTRIM0F WHERE T£CDMG NOT IN ('F1')

SELECT * FROM SMETSTBND.GMRRIM0F WHERE R£CDMG NOT IN ('F1') 

DELETE  FROM SMETSTBND.GMRRIM0F WHERE R£CDMG NOT IN ('F1')

SELECT * FROM SMETSTBND.V5TRIP0F WHERE V$CDOG NOT IN ('F1')

DELETE FROM SMETSTBND.V5TRIP0F WHERE V$CDOG NOT IN ('F1')


