


SELECT  DISTINCT(LEFT(D6NPRO, 3)) "Protocollo", 'FDA' "Azienda" FROM SMEDATFDA.V5STAT0F vsf 
WHERE D6NPRO<>''
UNION 
SELECT  DISTINCT(LEFT(D6NPRO, 3)) "Protocollo", 'LIZ' "Azienda" FROM SMEDATLIZ.V5STAT0F lsf 
WHERE D6NPRO<>''



SELECT * FROM SMEDATFDA.TABEL00F WHERE TTSETT='CRNC5'