

SELECT SUM(R5IMPO) AS "TOTALE PERIODO" FROM SMEDATBND.C5TREG0F INNER JOIN SMEDATBND.C5RREG0F ON R5PROG=T5PROG
WHERE  R5DAAV='A'                               
AND T5DREG BETWEEN 20230101 AND 20230228                      
UNION 
SELECT SUM(R5IMPO)*-1 AS "TOTALE PERIODO" FROM SMEDATBND.C5TREG0F INNER JOIN SMEDATBND.C5RREG0F ON R5PROG=T5PROG 
WHERE  R5DAAV='D'                                
 AND T5DREG BETWEEN 20230101 AND 20230228 
 
 
 SELECT * FROM SMEDATBND.DISTIN0F WHERE NRDS1D='A12V00003m' 
 
 
 SELECT * FROM SMEDATBND.GMQUAN0F 
 WHERE G§CDMG NOT IN ('F1', 'F7') 
 AND G§TIGC='PF' AND TRIM(G§COD3)=''
 
  
 SELECT * FROM SMEDATFDA.GMQUAN0F 
 WHERE  G§TIGC='10' AND TRIM(G§COD3)=''
 AND  G§CDMG <>'M1'
 
 
SELECT * FROM SMEDATBND.C£CONR0F WHERE C£NUMP='X75' AND C£TPRC='CLI' 

SELECT E§CRAG, E§NMNE, E§STAT, E§RAGS, E§INDI, E§LOCA, E§CAPA, E§PROV, E§ZONA, E§DT01, E§DT02, C£VALO "GG Dilazione Listino"
FROM SMEDATBND.BRENTI0F, SMEDATBND.C£CONR0F WHERE E§TRAG='CLI' AND C£TPRC='CLI' AND C£CD01=E§CRAG AND C£NUMP='X75'  
  AND E§DINV <= YEAR(CURRENT_DATE)*10000
                  + MONTH(CURRENT_DATE)*100
                  + DAY(CURRENT_DATE)
      AND E§DFNV >= YEAR(CURRENT_DATE)*10000
                  + MONTH(CURRENT_DATE)*100
                  + DAY(CURRENT_DATE) 
                  
SELECT --*
CAST("DT.LISTINO"  AS DECIMAL (8,0) )
FROM ced.clidilaz


SELECT * FROM CED.CLIDILAZ c  

UPDATE SMETSTBND.BRENTI0F A 
SET A.E§DT01=( SELECT CAST(B."DT.LISTINO"  AS DECIMAL (8,0) ) FROM CED.CLIDILAZ B WHERE B.E§CRAG=A.E§CRAG) 
WHERE A.E§TRAG='CLI' AND A.E§CRAG IN (SELECT X.E§CRAG FROM CED.CLIDILAZ X)
AND A.E§DINV <= YEAR(CURRENT_DATE)*10000
                  + MONTH(CURRENT_DATE)*100
                  + DAY(CURRENT_DATE)
AND A.E§DFNV >= YEAR(CURRENT_DATE)*10000
                  + MONTH(CURRENT_DATE)*100
                  + DAY(CURRENT_DATE) 

ALTER TABLE CED.PVEST90 ADD COLUMN MOV CHAR(1)

UPDATE CED.PVEST90 
SET MOV='1' 
WHERE F1 IN (SELECT DISTINCT T§CDCL FROM SMEDATBND.V5TDOC0F WHERE T§TCCL='PVE')

UPDATE  SMEDATBND.BRENTI0F 
SET E§LIVE='9' , E§STAT='90' 
WHERE E§TRAG='PVE' AND E§CRAG IN (SELECT F1 FROM CED.PVEST90 )--WHERE MOV<>'1') 
AND (E§STAT<>'90' AND E§LIVE<>'9')
AND E§DINV <= YEAR(CURRENT_DATE)*10000
                  + MONTH(CURRENT_DATE)*100
                  + DAY(CURRENT_DATE)
AND E§DFNV >= YEAR(CURRENT_DATE)*10000
                  + MONTH(CURRENT_DATE)*100
                  + DAY(CURRENT_DATE) 

                  
                 

                  
                  
                  SELECT * FROM smedatbnd.c£conr0f WHERE c£tprc='CLI' AND c£cd01='450696' 
                  
           WITH X AS (       
           SELECT E§CRAG FROM smedatbnd.brenti0f WHERE e§trag='CLI' AND 
            e§crag IN (SELECT c£cd01 FROM smedatbnd.c£conr0f WHERE c£tprc='CLI' AND c£nump='XD5')
           ) 
           SELECT * FROM SMEDATBND.V5TDOC0F WHERE T§TDOC='DA' AND T§CODF IN (SELECT * FROM X)
           
           
           
           
  SELECT * FROM SMEDATBND.C£LIST0F WHERE
    L§COD1 LIKE 'C45%' AND
    L§COD2 = 'MOD-MOD-M100'  AND
    --BETWEEN 'MOD-MOD-M100' AND 'MOD-MOD-M999'    AND 
    L§CL01 = 'CONTR-GMP'  
    
    non ha dato nessun risultato ==> nessun sconto presente con le caratteristiche indicate.
    
    
    
    SELECT * FROM SMEDATBND.C£CONR0F WHERE C£TPRC='C5B' AND C£NUMP='X01'
           