


SELECT * FROM SMEDATBND.BRARTI0F 
WHERE  A§DT10 = 0

DROP TABLE CED.OLDCD

CREATE TABLE CED.OLDCD ( OCDPV CHAR(15), NCDPV CHAR(15), SGPV CHAR(15), IDPV CHAR(10), RGPV CHAR(35), CLPV CHAR(15))

INSERT INTO CED.OLDCD 
SELECT E§CRAG, '       ', E§NMNE, E§IDOJ, E§RAGS, E§CCON   FROM SMETSTBND.BRENTI0F WHERE E§TRAG='PVE' AND E§CRAG IN 
(
'9166944',      
'9166945',        
'9166946',        
'9166947',        
'9166948',        
'9166949',        
'9166950',        
'9166951',        
'9166952',        
'9166953',        
'9166954',        
'9166955',        
'9166956',
'228895001',      
'228896001',      
'228897001',      
'228898001' 
)

SELECT  E§CRAG, E§NMNE, E§IDOJ, E§RAGS, E§CCON , CDPV, SGPV , IDPV , RGPV , CLPV FROM SMEtstBND.BRENTI0F, QTEMP.OLDCD 
WHERE E§TRAG='PVE' 
--AND E§CCON=CLPV 
AND E§IDOJ = IDPV
AND E§DINV <= YEAR(CURRENT_DATE) * 10000
                     + MONTH(CURRENT_DATE) * 100
                     + DAY(CURRENT_DATE)
       AND E§DFNV >= YEAR(CURRENT_DATE) * 10000
                     + MONTH(CURRENT_DATE) * 100
                     + DAY(CURRENT_DATE)
                     

UPDATE CED.OLDCD A
SET A.NCDPV=(SELECT B.E§CRAG FROM SMEDATBND.BRENTI0F B WHERE B.E§TRAG='PVE' AND B.E§IDOJ=A.IDPV) 
WHERE TRIM(A.NCDPV) IS NULL


UPDATE CED.OLDCD 
SET NCDPV='0229015' WHERE SGPV='N55WXM7'


SELECT * FROM CED.OLDCD 

SELECT * FROM EDP01.BRENTIWK 
WHERE E§IDOJ IN (SELECT IDPV FROM CED.OLDCD) 


SELECT

DELETE  FROM CED.OLDCD
WHERE IDPV IN (SELECT E§IDOJ FROM EDP01.BRENTIWK)

INSERT INTO EDP01.BRENTIWK ( E§SCEN, E§CRAG, E§NMNE, E§IDOJ, E§RAGS, E§CCON) SELECT * FROM CED.OLDCD 



        
        
D6TCDF     Tipo ente di fatturazione
D6CODF     Ente di fatturazione  

D6TCDS     Tipo ente di spedizione  
D6CODS     Ente di spedizione     

SELECT DISTINCT D6TCCL  FROM SMEDATFDA.V5STAT0F  

UPDATE SMEDATBND.V5STAT0F A 
SET A.D6CODS=(SELECT B.E§CRAG FROM EDP01.BRENTIWK B WHERE B.E§SCEN = A.D6CODS )
WHERE A.D6TCDS='PVE' AND A.D6CODS IN (SELECT X.E§SCEN FROM EDP01.BRENTIWK X)

SELECT * FROM SMEDATBND.V5STAT0F A
WHERE A.D6TCDS='PVE' AND A.D6CODS IN (SELECT X.E§SCEN FROM EDP01.BRENTIWK X)



