
DECLARE @OGGI CHAR(8);
SET OGGI = VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD');

WITH  X AS (
SELECT  UNSENTBLCD AS CDCLI, UNSENTSHCD AS CDPVE,  
  (CASE WHEN (UNSDOCTYPE IN ('F', 'D')  AND UNSEXPDATE >  VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD'))  THEN UNSVALUE  ELSE  0 END) AS ASCA_D, 
  (CASE WHEN (UNSDOCTYPE IN ('P', 'A')  AND UNSEXPDATE >  VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD'))  THEN UNSVALUE  ELSE  0 END) AS ASCA_A, 
  (CASE WHEN (UNSDOCTYPE IN ('F', 'D')  AND UNSEXPDATE <= VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD'))  THEN UNSVALUE  ELSE  0 END) AS SCAD_D, 
  (CASE WHEN (UNSDOCTYPE IN ('P', 'A')  AND UNSEXPDATE <= VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD'))  THEN UNSVALUE  ELSE  0 END) AS SCAD_A 
FROM NBFDATSTBN.BSOSPESI0F bf 
) 
SELECT X.CDCLI, X.CDPVE,
(SELECT E§RAGS  FROM SMETSTBND.BRENTI0F WHERE E§TRAG='CLI' AND E§CRAG=X.CDCLI) AS RAGSOC_CLI,
(SELECT E§ZONA  FROM SMETSTBND.BRENTI0F WHERE E§TRAG='PVE' AND E§CRAG=X.CDPVE) AS ZONA, 
SUM(X.ASCA_D) AS ASCADERE_DARE, SUM(X.ASCA_A) AS ASCADERE_AVERE,
SUM(X.SCAD_D) AS SCADUTO_DARE, SUM(X.SCAD_A) AS SCADUTO_AVERE,
(SUM(X.ASCA_D) - SUM(X.ASCA_A)) AS TOTALE_ASCADERE,
(SUM(X.SCAD_D) - SUM(X.SCAD_A)) AS TOTALE_SCADUTO,
((SUM(X.ASCA_D) - SUM(X.ASCA_A))+ (SUM(X.SCAD_D) - SUM(X.SCAD_A))) AS SALDO
FROM X  
GROUP BY X.CDCLI, X.CDPVE , (SELECT E§ZONA FROM SMETSTBND.BRENTI0F WHERE E§TRAG='PVE' AND E§CRAG=X.CDPVE)
ORDER BY X.CDCLI, ZONA;

SELECT VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD') FROM SYSIBM.SYSDUMMY1 INTO OGGI

X AS 
SELECT * FROM OGGI




DECLARE @INPUT_VALUE INT
SET INPUT_VALUE = 4756

SELECT *
FROM TABLE1
WHERE TABLE1.COLUMN1 = @INPUT_VALUE

SELECT VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD') INTO OGGI FROM SYSIBM.SYSDUMMY1 
SELECT OGGI FROM 1;

SELECT * FROM CED.C£CONR0FBN

INSERT INTO CED.C£CONR0X68
SELECT * FROM SMEDATBND.C£CONR0F
WHERE "C£NUMP"='X68'  