


SELECT PRESALESID, [ZONE], CAUSALE, ITEMID, LINEAMOUNT, LINENUM, SALESPRICE, SALESQTY, BASKET, 
DESCRIZIONE_TORTA, STATO, DT_SYS, COMPANY, KHEADER, CRD_ZONE 
FROM BINDIGEST.dbo.PV_OUT_0003_RigaOrdine;


SELECT AMOUNTTOTAL, ORDERID, PRESALESDATE, PRESALESTIME, PRESALESID, REQESTEDDELIVERYDATE, 
[ZONE], CUSTACCOUNT, BND_384_DST, BND_CUSTTRATTA, CUSTOMERREF, NOTE, STATO, DT_SYS, 
COMPANY, KHEADER, CRD_ZONE FROM BINDIGEST.dbo.PV_OUT_0002_TestataOrdine;


SELECT COUNT( DISTINCT (KHEADER)) FROM BINDIGEST.dbo.PV_OUT_0002_TestataOrdine 

SELECT KHEADER, COUNT(KHEADER) FROM BINDIGEST.dbo.PV_OUT_0002_TestataOrdine  
GROUP BY KHEADER HAVING COUNT(KHEADER)>1
