

SELECT * FROM SMEDATLIZ.BRDIST0F bf 
WHERE D§STAT='10' AND  D§TIPD='ART' 
AND D§ASSI IN (
SELECT 
DISTINCT D§ASSI
FROM SMEDATLIZ.BRDIST0F  
WHERE D§STAT='10' AND  D§TIPD='ART' 
ORDER BY D§ASSI
)


SELECT * FROM SMEDATGRU5.SPLUSR01

SELECT * FROM SMEDATLIZ.BRENTI0F WHERE E§TRAG='CLI' AND E§CRAG='902248' 
AND E§DFNV >=  VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD') 
AND E§STAT='10'
UNION 
SELECT * FROM SMEDATLIZ.BRENTI0F WHERE E§TRAG='PVE' AND E§TCON='CLI' AND E§CCON='902248' 
AND E§DFNV >=  VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD') 
AND E§STAT='10' 
ORDER BY E§TRAG

COMMIT

UPDATE SMEDATLIZ.BRENTI0F 
SET E§NUM3='9999' 
WHERE E§TRAG='PVE' 
AND E§TCON='CLI' AND E§CCON='902248' 
AND E§DFNV >=  VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD') 
AND E§STAT='10' 
