
-- 12/11/2023 IMPOSTAZIONE BLOCCHI SU ZONE AGENTI CAGLIARI FIRENZE E PAVIA 
UPDATE SMEDATBND.TABEL00F T
SET TTUSER=CONCAT(CONCAT(CONCAT(CONCAT(SUBSTRING(TTUSER, 1, 3), 'G'), SUBSTRING(TTUSER, 5, 7)), '30'), SUBSTRING(TTUSER, 14, LENGTH(TTUSER)))
WHERE TTSETT ='ZON'
AND TTELEM  IN 
('C02', 'S00', 'S01', 'S02', 'S03', 'S04', 'S05', 'S06', 'S07', 'S08', 'S09', 'S10', 'S11', 'C05', 'L08', 'L10', 'L11', 'L09', 'A02', 'P01', 'P02', 'P03', 'P04', 'P08', 'P09' )


-- VERIFICA CANALE DI VENDITA SUI PVE SERVITI DALLE ZONE DI CUI SOPRA
WITH X AS (
SELECT E§TRAG, E§NMNE, E§STAT, E§CRAG, E§RAGS, E§ZONA, E§COD1, E§COD8, E§TCON, E§CCON  
FROM SMEDATBND.BRENTI0F  WHERE E§TRAG='PVE'  
AND E§DINV <  VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD') 
AND E§DFNV >= VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD')
AND E§ZONA IN 
('C02', 'S00', 'S01', 'S02', 'S03', 'S04', 'S05', 'S06', 'S07', 'S08', 'S09', 'S10', 'S11', 'C05', 'L08', 'L10', 'L11', 'L09', 'A02', 'P01', 'P02', 'P03', 'P04', 'P08', 'P09' )
), Y AS (
SELECT E§TRAG, E§CRAG,E§NMNE,E§STAT,E§RAGS FROM SMEDATBND.BRENTI0F  
WHERE
    E§DINV <  VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD') 
AND E§DFNV >= VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD')
)
SELECT  
/*x.E§TCON AS "Tipo   CLI",*/
x.E§CCON AS "Codice CLI;CNCLI",
y.E§NMNE AS "Sigla  CLI",
y.E§STAT AS "Stato  CLI",
y.E§RAGS AS "Ragione Sociale CLI",
/*x.E§TRAG AS "Tipo   PVE",*/
x.E§CRAG AS "Codice PVE;CNPVE",
x.E§NMNE AS "Sigla  PVE",
x.E§STAT AS "Stato  PVE",
x.E§RAGS AS "Ragione Sociale PVE",
x.E§ZONA AS "Zona", 
x.E§COD1 AS "Magazzino",
x.E§COD8 AS "Canale di Vendita"
FROM X,Y WHERE x.E§TCON=y.E§TRAG AND x.E§CCON=y.E§CRAG  AND x.E§COD8='000'
ORDER BY
/*"Tipo   CLI",*/
"Stato  CLI","Codice CLI;CNCLI" 


SELECT * FROM SMEDATBND.BRENTI0F 

UPDATE SMEDATBND.BRENTI0F 
SET E§COD8='DET'  
WHERE E§TRAG='PVE' AND E§COD8='000' AND E§ZONA IN 
('C02', 'S00', 'S01', 'S02', 'S03', 'S04', 'S05', 'S06', 'S07', 'S08', 'S09', 'S10', 'S11', 'C05', 'L08', 'L10', 'L11', 'L09', 'A02', 'P01', 'P02', 'P03', 'P04', 'P08', 'P09' )
AND E§DINV <  VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD') 
AND E§DFNV >= VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD')

SELECT * FROM SMEDATBND.BRENTI0F 

UPDATE SMEDATBND.BRENTI0F 
SET E§COD8='DET' 
WHERE E§TRAG='CLI' AND E§LIVE='2' 
AND E§DINV <  VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD') 
AND E§DFNV >= VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD')
AND E§CRAG IN (
SELECT DISTINCT E§CCON FROM SMEDATBND.BRENTI0F 
WHERE E§TRAG='PVE'  AND E§ZONA IN 
('C02', 'S00', 'S01', 'S02', 'S03', 'S04', 'S05', 'S06', 'S07', 'S08', 'S09', 'S10', 'S11', 'C05', 'L08', 'L10', 'L11', 'L09', 'A02', 'P01', 'P02', 'P03', 'P04', 'P08', 'P09' )
AND E§DINV <  VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD') 
AND E§DFNV >= VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD')
)
