

WITH ZAI AS ( SELECT
XZA.TTELEM "AREA",
XZA.TTDESC "DESCR_AREA",
XCA.TTELEM "CAPOAREA",
XCA.TTDESC "DESCR_CAPO_AREA",
XZI.TTELEM "ZONA_ISPETTIVA",
XZI.TTDESC "DESCR_ZONA_ISPETTIVA",
ISP.C£CDVA "ISPETTORE",
XIS.TTDESC "NOME_ISPETTORE",
TRIM(ZON.TTELEM) "ZONA",
ZON.TTDESC "DESCR_ZONA",
AGE.C£CDVA "AGENTE",
TAGE.TTDESC "NOME_AGENTE",
SUBSTR(ZON.TTUSER, 26, 2) "MAG_SERVIZIO"
FROM SMEDATFDA.TABEL00F ZON
LEFT OUTER JOIN SMEDATFDA.C£CONR0F AGE
ON AGE.C£TPRC = 'ZON' AND AGE.C£NUMP = 'ZAG' AND AGE.C£CD01=ZON.TTELEM
LEFT JOIN SMEDATFDA.TABELD0F TAGE
ON TAGE.TTSETT='AGE' AND TAGE.TTELEM=AGE.C£CDVA
LEFT OUTER JOIN SMEDATFDA.TABEL00F XZI
ON XZI.TTSETT='XZI' AND XZI.TTELEM=LEFT(ZON.TTUSER, 3)
LEFT OUTER JOIN SMEDATFDA.C£CONR0F ISP
ON ISP.C£TPRC='XZI' AND ISP.C£NUMP='XZA' AND ISP.C£CD01=XZI.TTELEM
LEFT JOIN SMEDATFDA.TABEL00F XIS
ON XIS.TTSETT='XIS' AND XIS.TTELEM=ISP.C£CDVA
LEFT JOIN SMEDATFDA.TABEL00F XZA
ON XZA.TTSETT='XZA' AND XZA.TTELEM=LEFT(TRIM(XZI.TTLIBE),3)
LEFT JOIN SMEDATFDA.C£CONR0F TXZA
ON XZA.TTSETT='XZA' AND TXZA.C£CD01=XZA.TTELEM
LEFT JOIN SMEDATFDA.TABEL00F XCA
ON XCA.TTSETT='XCA' AND TXZA.C£CDVA=XCA.TTELEM
WHERE ZON.TTSETT='ZON'
AND COALESCE(AGE.C£DTIN, 0) <= YEAR(CURRENT_DATE) * 10000
+ MONTH(CURRENT_DATE) * 100
+ DAY(CURRENT_DATE)
AND (COALESCE(AGE.C£DTFN, 0) = 0
OR COALESCE(AGE.C£DTFN, 99999999) >= YEAR(CURRENT_DATE) * 10000
+ MONTH(CURRENT_DATE) * 100
+ DAY(CURRENT_DATE))
AND COALESCE(ISP.C£DTIN, 0) <= YEAR(CURRENT_DATE) * 10000
+ MONTH(CURRENT_DATE) * 100
+ DAY(CURRENT_DATE)
AND (COALESCE(ISP.C£DTFN, 0) = 0
OR COALESCE(ISP.C£DTFN, 99999999) >= YEAR(CURRENT_DATE) * 10000
+ MONTH(CURRENT_DATE) * 100
+ DAY(CURRENT_DATE))
AND COALESCE(TXZA.C£DTIN, 0) <= YEAR(CURRENT_DATE) * 10000
+ MONTH(CURRENT_DATE) * 100
+ DAY(CURRENT_DATE)
AND (COALESCE(TXZA.C£DTFN, 0) = 0
OR COALESCE(TXZA.C£DTFN, 99999999) >= YEAR(CURRENT_DATE) * 10000
+ MONTH(CURRENT_DATE) * 100
+ DAY(CURRENT_DATE))
ORDER BY ZON.TTELEM ),
X AS (
SELECT E§TRAG TE, E§CRAG CE, E§COPA CPG, E§TPRZ TP, E§CPRZ CP FROM SMEDATFDA.BRENTI0F
WHERE E§TRAG='CLI' 
AND E§DINV <  VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD') 
AND E§DFNV >= VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD')
)                  
SELECT E§CRAG AS CODCLIENTE,
 E§NMNE AS CODMNEMONICOCLIENTE,
 E§TRAG AS TIPOCLIENTE,
 E§RAGS AS RAGIONESOCIALE,
 E§RAGA AS RAGIONESOCIALEAGGIUNTIVA,
 TRIM(E§CRAG)||' - '||TRIM(E§RAGS) AS EXTNUMDESCCLIENTE,
 TRIM(E§NMNE)||' - '||TRIM(E§RAGS) AS EXTMNEDESCCLIENTE,
 E§CCON AS CODCLIENTEFAT,
 E§GRUP AS CODCATEGORIAENTE,
 E§STAT AS CODSTATO,
 E§INDI AS INDIRIZZO,
 E§CAPA AS POSTCODE,
 TRIM(E§CNAZ)||TRIM(E§COD4) AS CODCOMUNE,
 TRIM(E§CNAZ)||TRIM(E§PROV) AS CODPROVINCIA,
 TRIM(E§CNAZ)||TRIM(E§CREG) AS CODREGIONE,
 E§CNAZ AS CODNAZIONE,
 E§CSME AS CODSETTOREMERCEOLOGICO,
 COALESCE(TRIM(C£CDVA), 'NON CODIFICATO') AS CATEGORIANEW,
  CASE E§FL20 WHEN  '' THEN 'SI' ELSE 'NO' END  AS CLIENTE_BLOCCATO,
 CASE WHEN SUBSTRING(E§COD2,1,1)<>'' THEN 'Lunedì' ELSE '' END AS GIORNOVISITA1,
 CASE WHEN SUBSTRING(E§COD2,2,1)<>'' THEN 'Martedì' ELSE '' END AS
GIORNOVISITA2,
 CASE WHEN SUBSTRING(E§COD2,3,1)<>'' THEN 'Mercoledì' ELSE '' END AS
GIORNOVISITA3,
 CASE WHEN SUBSTRING(E§COD2,4,1)<>'' THEN 'Giovedì' ELSE '' END AS
GIORNOVISITA4,
 CASE WHEN SUBSTRING(E§COD2,5,1)<>'' THEN 'Venerdì' ELSE '' END AS
GIORNOVISITA5,
 CASE WHEN SUBSTRING(E§COD2,6,1)<>'' THEN 'Sabato' ELSE '' END AS GIORNOVISITA6,
 CASE WHEN SUBSTRING(E§COD2,7,1)<>'' THEN 'Domenica' ELSE '' END AS
GIORNOVISITA7,
  (SELECT COALESCE(MIN(TRIM(C£CDVA)), ' ')
          FROM SMEDATFDA.C£CONR0F
          WHERE C£TPRC='PVE' AND C£CD01=E§CRAG AND C£CD02=''
                AND C£NUMP='GC1') AS "CLUN",
       (SELECT COALESCE(MIN(TRIM(C£CDVA)), ' ')
          FROM SMEDATFDA.C£CONR0F
          WHERE C£TPRC='PVE' AND C£CD01=E§CRAG AND C£CD02=''
                AND C£NUMP='GC2') AS "CMAR",
       (SELECT COALESCE(MIN(TRIM(C£CDVA)), ' ')
          FROM SMEDATFDA.C£CONR0F
          WHERE C£TPRC='PVE' AND C£CD01=E§CRAG AND C£CD02=''
                AND C£NUMP='GC3') AS "CMER",
       (SELECT COALESCE(MIN(TRIM(C£CDVA)), ' ')
          FROM SMEDATFDA.C£CONR0F
          WHERE C£TPRC='PVE' AND C£CD01=E§CRAG AND C£CD02=''
                AND C£NUMP='GC4') AS "CGIO",
       (SELECT COALESCE(MIN(TRIM(C£CDVA)), ' ')
          FROM SMEDATFDA.C£CONR0F
          WHERE C£TPRC='PVE' AND C£CD01=E§CRAG AND C£CD02=''
                AND C£NUMP='GC5') AS "CVEN",
       (SELECT COALESCE(MIN(TRIM(C£CDVA)), ' ')
          FROM SMEDATFDA.C£CONR0F
          WHERE C£TPRC='PVE' AND C£CD01=E§CRAG AND C£CD02=''
                AND C£NUMP='GC6') AS "CSAB",
       (SELECT COALESCE(MIN(TRIM(C£CDVA)), ' ')
          FROM SMEDATFDA.C£CONR0F
          WHERE C£TPRC='PVE' AND C£CD01=E§CRAG AND C£CD02=''
                AND C£NUMP='GC7') AS "CDOM",
       '[' || SUBSTRING(E§COD3, 1, 7) || ']' AS CHIUSURA,
       E§COD8 AS CLASSCOMM,
       E§COD7 AS SUBZONAGE,
       E§NUM7 AS SHAPEID,
 E§COD1 AS CODPIATTAFORMA,
 E§COD5 AS LAT,
 E§COD6 AS LON,
 X.CPG AS CODPAGAM,
 ZONA AS CODZONAVENDITA,
 trim(ZONA)||'-'||trim(AGENTE) AS K_AGE,
 E§COD9 AS MARCHIO,
 X.TP AS TIPOENTETRATTPREZZO,
 X.CP AS CODENTETRATTPREZZO,
 --TIPO_ZONA AS TIPOZONAVENDITA,
 AGENTE AS CODAGENTE,
 ZONA_ISPETTIVA AS CODZONAISPETTIVA,
 ISPETTORE AS CODISPETTORE_TMP,
 NOME_ISPETTORE,
 AREA AS CODAREA,
 CAPOAREA AS CODCAPOAREA,
 DESCR_CAPO_AREA AS CAPOAREA
 FROM SMEDATFDA.BRENTI0F
LEFT OUTER JOIN ZAI ON E§ZONA=ZONA
LEFT OUTER JOIN X ON E§TCON=X.TE AND E§CCON=X.CE
LEFT OUTER JOIN SMEDATFDA.C£CONR0F CAT ON CAT.C£TPRC='PVE' AND CAT.C£NUMP='D01' AND E§CRAG = CAT.C£CD01
WHERE E§TRAG='PVE'  --AND E§CRAG='0212244'
AND E§DINV <  VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD') 
AND E§DFNV >= VARCHAR_FORMAT(CURRENT_DATE, 'YYYYMMDD')
