

SELECT articolo, sito, magazzino, lotto, udc, data_scadenza, giacenza
FROM AXIB_ALS.dbo.Edo_ESTR_GIACENZA_AX_TUTTI_DETTAGLIO_SMEUP; 


SELECT DISTINCT SITO FROM 
AXIB_ALS.dbo.Edo_ESTR_GIACENZA_AX_TUTTI_DETTAGLIO_SMEUP;  


select count(*) from  
AXIB_ALS.dbo.Edo_ESTR_GIACENZA_AX_TUTTI_DETTAGLIO_SMEUP WHERE 
--SITO='01' AND MAGAZZINO='TL'   -- ASSAGO 1032 RECORD
--SITO='02' AND MAGAZZINO='RM'   -- ROMA 809 RECORD
--SITO='06' AND MAGAZZINO='FI'   -- FIRENZE 969 RECORD
--SITO='07' AND MAGAZZINO='CA'   -- CAGLIARI  554 RECORD 



SELECT DISTINCT trasportatore_prefer 
from AXIB_ALS.dbo.Edo_ESTR_CLIENTI_SMEUP eecs  


SELECT *
from AXIB_ALS.dbo.Edo_ESTR_VETTORI_SMEUP eevs 
