
-- 29/04/2023 OPERAZIONI POST EXPORT DATI DA AX E PRE PARTENZA FILIALI
-- Assegnazione giacenze ricevute alle ubicazioni presenti.
-- N.B. le assegnazioni ricevute da Callegaro e fornite da Unilogistica

-- ASSEGNAZIONE ARTICOLO/UBICAZIONE MAGAZZINO F3 MILANO  
UPDATE SMEDATBND.GMQUAN0F A  
SET A.G§COD3= (SELECT B.UBICAZIONE FROM CED.ARTUBICF3 B WHERE  B.UBICAZIONE <>'' AND B.ARTICOLO<>'' AND A.G§ARTI=B.ARTICOLO )
WHERE  A.G§TIGC='PF' AND A.G§SOGC='UB' AND A.G§CDMG='F3'   AND A.G§ARTI<>'' 
AND A.G§ARTI IN ( SELECT DISTINCT ARTICOLO FROM CED.ARTUBICF3) 

-- VERIFICA UPDATE 
SELECT B.A§DEAR,A.* FROM  SMEDATBND.GMQUAN0F A  INNER JOIN SMEDATBND.BRARTI0F B ON B.A§ARTI=A.G§ARTI
--WHERE  A.G§TIGC='TC'                     -- area logica TC ??????  
WHERE  A.G§TIGC='PF'  AND G§SOGC='UB'    -- area logica PF
AND A.G§CDMG='F3'   AND A.G§ARTI<>'' 



-- ASSEGNAZIONE ARTICOLO/UBICAZIONE MAGAZZINO F6 FIRENZE   
UPDATE SMEDATBND.GMQUAN0F A  
SET A.G§COD3= (SELECT B.UBICAZIONE FROM CED.ARTUBICF6 B WHERE  B.UBICAZIONE <>'' AND B.ARTICOLO<>'' AND A.G§ARTI=B.ARTICOLO )
WHERE  A.G§TIGC='PF' AND A.G§SOGC='UB' AND A.G§CDMG='F6'   AND A.G§ARTI<>'' 
AND A.G§ARTI IN ( SELECT DISTINCT ARTICOLO FROM CED.ARTUBICF6) 

-- VERIFICA UPDATE 
SELECT B.A§DEAR,A.* FROM  SMEDATBND.GMQUAN0F A  INNER JOIN SMEDATBND.BRARTI0F B ON B.A§ARTI=A.G§ARTI
--WHERE  A.G§TIGC='TC'                     -- area logica TC ??????  
WHERE  A.G§TIGC='PF'  AND G§SOGC='UB'    -- area logica PF
AND A.G§CDMG='F6'   AND A.G§ARTI<>'' 


ALTER TABLE CED.ARTUBICF6 RENAME COLUMN CODIC00001 TO  ARTICOLO 

RENAME COLUMNE CED.ARTUBICF6."CODICE ARTICOLO" TO "ARTICOLO"


INSERT INTO CED.BRENTIWK1 (
WITH A AS
(
SELECT B.* , 
        ROW_NUMBER() OVER (PARTITION BY e§crag ORDER BY e§crag DESC) AS RN
        FROM CED.BRENTI0F AS B
)
SELECT E§TRAG, E§CRAG, E§SCEN, E§AZIE, E§IDOJ, E§DINV, E§DFNV, E§GRUP, E§NMNE, 
E§NCOD, E§LIVE, E§STAT, E§RAGS, E§RAGA, E§INDI, E§INDA, E§TELE, E§TFAX, E§TELX, 
E§IEMA, E§PECO, E§CNAZ, E§CREG, E§CCOM, E§LOCA, E§PROV, E§NAZI, E§CAPA, E§ZONA, 
E§LING, E§VALU, E§TSOG, E§CPAI, E§COFI, E§CPAE, E§CTA1, E§CTA2, E§CTA3, E§DVES, 
E§CDIN, E§DDIN, E§TNOM, E§CNOM, E§TSPE, E§CSPE, E§TCON, E§CCON, E§TINC, E§CINC, 
E§TPRZ, E§CPRZ, E§TCRR, E§CCRR, E§TVET, E§CVET, E§CACO, E§CACR, E§CLAB, E§CLAV, 
E§CSME, E§CONS, E§SPED, E§IMBA, E§CAUS, E§GCHI, E§GCON, E§GCOL, E§AGEN, E§PERP, 
E§AGE1, E§PER1, E§CRCP, E§COPA, E§CSP1, E§CSP2, E§CSP3, E§CSP4, E§CSP5, E§LIST, 
E§SCON, E§PRIO, E§FIDO, E§BANC, E§CCOR, E§CBA2, E§IBAN, E§SWIF, E§CBA3, E§DTIE, 
E§DT01, E§DT02, E§DT03, E§DT04, E§DT05, E§DT06, E§DT07, E§DT08, E§DT09, E§DT10, 
E§COD1, E§COD2, E§COD3, E§COD4, E§COD5, E§COD6, E§COD7, E§COD8, E§COD9, E§COD0, 
E§NUM1, E§NUM2, E§NUM3, E§NUM4, E§NUM5, E§NUM6, E§NUM7, E§NUM8, E§NUM9, E§NUM0, 
E§FL01, E§FL02, E§FL03, E§FL04, E§FL05, E§FL06, E§FL07, E§FL08, E§FL09, E§FL10, 
E§FL11, E§FL12, E§FL13, E§FL14, E§FL15, E§FL16, E§FL17, E§FL18, E§FL19, E§FL20, 
E§FL21, E§FL22, E§FL23, E§FL24, E§FL25, E§FL26, E§FL27, E§FL28, E§FL29, E§FL30, 
E§FL31, E§FL32, E§FL33, E§FL34, E§FL35, E§FL36, E§FL37, E§FL38, E§FL39, E§FL40, 
E§ORIN, E§DTIN, E§USIN, E§ORAG, E§DTAG, E§USAG 
FROM A WHERE RN  1 
ORDER BY E§CRAG
)

DELETE T
FROM
(

CREATE TABLE QTEMP.IDVETT ( IDV CHAR(10))

DELETE FROM CED.BRENTI0F WHERE E§IDOJ IN (

INSERT INTO QTEMP.IDVETT 
WITH T AS (
SELECT B.* ,
 ROW_NUMBER() OVER (
              PARTITION BY E§CRAG
              ORDER BY E§CRAG
            ) AS DUPRANK 
FROM CED.BRENTI0F AS B
)
SELECT E§IDOJ FROM  T
WHERE DUPRANK > 1 
ORDER BY E§CRAG 

DELETE FROM CED.BRENTI0F WHERE E§IDOJ IN (SELECT IDV  FROM QTEMP.IDVETT) 



SELECT * FROM CED.BRENTI0F ORDER BY E§CRAG


SELECT * FROM SMEDATBND.GMUBIC0F 

SELECT COUNT(*) FROM CED.C£CONR0X68
WHERE C£NUMP='X68' AND C£TPRC='CLI'


SELECT TTELEM, LEFT(TTLIBE, 2) FROM SMEDATBND.TABEL00F WHERE TTSETT='XGI'

UPDATE CED.C£CONR0FWK A
SET A.C£CD02=(SELECT B.E§COD1 FROM SMEDATBND.BRENTI0F B WHERE B.E§TRAG='PVE' AND B.E§CRAG=A.C£CD01)
WHERE A.C£TPRC='PVE'


SELECT * FROM CED.C£CONR0FWK 
WHERE --C£CD02='F1' AND 
C£CDVA NOT IN (
SELECT TTELEM FROM SMEDATBND.TABEL00F WHERE TTSETT='XGI'
)

UPDATE CED.C£CONR0FWK 
SET C£CDVA='F1DET' 
WHERE C£CD02='F1' AND C£CDVA NOT IN (
SELECT TTELEM FROM SMEDATBND.TABEL00F WHERE TTSETT='XGI'


UPDATE CED.C£CONR0FWK 
SET 
C£DTAG=20230429,
C£ORAG=171500  ,
C£USAG='EDP01SQL',  
C£OGAG='DBEAVER'


INSERT INTO SMEDATBND.C£CONR0F (SELECT * FROM  CED.C£CONR0FWK)

COMMIT
