


SELECT DISTINCT DAY(UNSDATAINS) FROM NBFDATTST.SOSPESI0F sf

SELECT DISTINCT DAY(UNSDATAINS) FROM NBFDAT.SOSPESI0F sf


DELETE FROM NBFDAT.SOSPESI0F WHERE DAY(UNSDATAINS) <> 6

COMMIT 


SELECT DISTINCT ENTID FROM NBFDAT.OENTITY A

WITH A AS
(
	SELECT B.* , 
        ROW_NUMBER() OVER (PARTITION BY ENTID ORDER BY ENTID DESC) AS RN
	FROM NBFDAT.OENTITY AS B
)
SELECT 
MAX(A.ENTID),A.* 
FROM A 
GROUP BY A.ENTID

INSERT INTO NBFDAT.BENTITY 
(
WITH A AS ( 
SELECT DISTINCT CONCAT(ENTTYPE,ENTNUMCODE), MAX(RRN(O)) AS RN FROM NBFDAT.OENTITY o 
GROUP BY CONCAT(ENTTYPE,ENTNUMCODE)
) 
SELECT * FROM NBFDAT.OENTITY Z WHERE RRN(Z) IN (SELECT RN FROM A)
)


SELECT count(o.ENTID) FROM NBFDAT.OENTITY o 
WHERE o.ENTID =765215

SELECT * FROM smedatliz.brenti0f 
WHERE e§stat='86' 



SELECT * FROM SMEDAT_TS2.c£list0f   
WHERE l§cdli='501' AND l§cod2='020517' 
LIMIT 100

WITH X AS (
SELECT E§TRAG, E§NMNE, E§STAT, E§CRAG, E§RAGS, E§COD8, E§TCON, E§CCON  
FROM SMEDATLIZ.BRENTI0F  WHERE E§TRAG='PVE'  
AND E§DINV <= YEAR(CURRENT_DATE)*10000
                  + MONTH(CURRENT_DATE)*100
                  + DAY(CURRENT_DATE) 
AND E§DFNV >= YEAR(CURRENT_DATE)*10000
                  + MONTH(CURRENT_DATE)*100
                  + DAY(CURRENT_DATE)            
), Y AS (
SELECT E§TRAG, E§CRAG,E§NMNE,E§STAT,E§RAGS FROM SMEDATLIZ.BRENTI0F  
WHERE 
 E§DINV <= YEAR(CURRENT_DATE)*10000
                  + MONTH(CURRENT_DATE)*100
                  + DAY(CURRENT_DATE) 
AND E§DFNV >= YEAR(CURRENT_DATE)*10000
                  + MONTH(CURRENT_DATE)*100
                  + DAY(CURRENT_DATE)
)
SELECT  
/*x.E§TCON AS "Tipo   CLI",*/
x.E§CCON AS "Codice CLI;CNCLI",
y.E§NMNE AS "Sigla  CLI",
y.E§STAT AS "Stato  CLI",
y.E§RAGS AS "Ragione Sociale CLI",
/*x.E§TRAG AS "Tipo   PVE",*/
x.E§CRAG AS "Codice PVE;CNPVE",
x.E§NMNE AS "Sigla  PVE",
x.E§STAT AS "Stato  PVE",
x.E§RAGS AS "Ragione Sociale PVE",
x.E§COD8 AS "Canale di Vendita"
FROM X,Y WHERE x.E§TCON=y.E§TRAG AND x.E§CCON=y.E§CRAG  
ORDER BY 
/*"Tipo   CLI",*/
"Stato  CLI","Codice CLI;CNCLI"


